### ISSUE TITLE
Documentos comerciais de fornecedores

### ISSUE THREAD

**Issue by progsoftpack** [assoft-portugal/SAF-T-AO#10]
Ao tentar validar o ficheiro de documentos comerciais de fornecedores, existem algumas incoerências com o ficheiro de validação xsd, em relação à lei.

Composição do saft na lei (a) vs no xsd (b):

            a) na lei: 
                            <InvoiceDate></InvoiceDate>
                            <Period></Period>
                            <InvoiceType></InvoiceType>
                            <SourceID></SourceID>
                            <SupplierID></SupplierID>
                            <InvoiceNo></InvoiceNo>
                            <DocumentTotals>
                                    <InputTax></InputTax>
                                    <TaxBase></TaxBase>
                                    <GrossTotal></GrossTotal>
                            </DocumentTotals>

            b) no xsd:
                            <InvoiceNo></InvoiceNo>
                            <Period></Period>
                            <InvoiceDate></InvoiceDate>
                            <InvoiceType></InvoiceType>
                            <SourceID></SourceID>
                            <SupplierID></SupplierID>
                            <DocumentTotals>
                                    <InputTax></InputTax>
                                    <TaxPayable></TaxPayable>
                                    <NetTotal></NetTotal>
                                    <GrossTotal></GrossTotal>
                            `</DocumentTotals>`

Incoerências identificadas:
1. ordenação dos elementos;
2. composição do elemento "DocumentTotals", em que, na lei existem 3 elementos: InputTax, TaxBase e GrossTotal; e no xsd temos: InputTax, TaxPayable, NetTotal e GrossTotal.

**Comment by cryptolopes** [comment]
A estrutura de fornecedores vai ser profundamente revista, com a inclusão de um conjunto de novo elementos. É possível visualizar em [Resources](https://github.com/assoft-portugal/SAF-T-AO/tree/master/Resources).
Porém esta versão já contempla algumas alterações que foram propostas pela AGT.

**Comment by MiguelSilva-PBSS** [comment]
Boa tarde,

ao validar o xml dos "documentos comerciais de fornecedores" com o xsd encontrei o seguinte problema:

![PurchasesInvoices](https://user-images.githubusercontent.com/53896958/63032696-3ab46a80-beae-11e9-9d0e-8b58dcb3177c.PNG)

Como a estrutura dos fornecedores vai ser revista, deixo este alerta.

Cumprimentos.

**Comment by cryptolopes** [comment]
Duplicate of #20
