### ISSUE TITLE
Documentos de Compra com mais de uma tipologia

### ISSUE THREAD

**Issue by cacimboerp** [assoft-portugal/SAF-T-AO#100]
É comum efetuar compras de mercadoria e bens de consumo ou mesmo imobilizado no mesmo documento.
Nesse caso, seria possível inserir mais do que uma linha para :

4.5.2.8.4.4 | * | Tipologia ou linha de destino para DP de IVA (DeductibeTaxType) 

??

**Comment by cryptolopes** [comment]
Olá @cacimboerp!

Isso é possível. A estrutura do SAF-T prevê isso `maxOccurs="unbounded".`

https://github.com/assoft-portugal/SAF-T-AO/blob/97c7d2006b5037471261e7f8d97e752785fe33f9/XSD/SAFTAO1.01_01.xsd#L699-L700

https://github.com/assoft-portugal/SAF-T-AO/blob/97c7d2006b5037471261e7f8d97e752785fe33f9/XSD/SAFTAO1.01_01.xsd#L1906-L1925
