### ISSUE TITLE
Worktype para Proforma

### ISSUE THREAD

**Issue by viegasfh** [assoft-portugal/SAF-T-AO#102]
Olá!

Relativamente aos WorkDocuments, no Schema é descrito que o valor PF é usado quando o WorkType é uma proforma. Contudo, no decreto presidencial vem como PP. Nas restrictions temos tanto o valor PF quanto o PP, o que quer dizer que qualquer um destes valores é aceite. No entanto, a AGT obriga a usar o PP e invalida o PF, que presumo que seja por causa do decreto.

No schema foi adicionado o valor PF por engano? Ou PF também é válido para proformas?

Partilho aqui o screenshot da declaração do WorkType:

![image](https://user-images.githubusercontent.com/290857/96516031-4c399500-125e-11eb-9fc2-2d87813125b8.png)

**Comment by cryptolopes** [comment]
Duplicate of #6 
ver https://github.com/assoft-portugal/SAF-T-AO/issues/6#issuecomment-516562273
