### ISSUE TITLE
XSD Purchase Invoices

### ISSUE THREAD

**Issue by josesantosmerino** [assoft-portugal/SAF-T-AO#103]
Bom dia,

estou a analisar o conteúdo do XSD anexado neste portal e verifico que a estrutura é diferente da mencionada no decreto presidencial emitido pelo Governo de Angola.

Poderiam ajudar-me a entender com que fundamento o XSD para a Purchase Invoices está diferente do referido no Decreto presidencia? Será o formato do XSD que deveremos considerar?

Muito obrigado.

[DP_312_18.pdf](https://github.com/assoft-portugal/SAF-T-AO/files/5445257/DP_312_18.pdf)

<xs:element minOccurs="0" name="PurchaseInvoices">
          <xs:complexType>
            <xs:annotation>
              <xs:documentation>
                Documentos comerciais de Fornecedores
              </xs:documentation>
            </xs:annotation>
            <xs:sequence>
              <xs:element ref="NumberOfEntries" />
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Invoice">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="InvoiceNo" type="ns:SAFAOtextTypeMandatoryMax60Car" />
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="References" type="PurchaseReferences" />
                    <xs:element ref="Hash">
                      <xs:annotation>
                        <xs:documentation>
                          Preencher com os 4 valores correspondentes ao Hash constantes no documento impresso. 
                          O campo deve ser preenchido com “0” (zero), caso não haja obrigatoriedade de validação.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element ref="SourceID" />
                    <xs:element minOccurs="0" ref="Period" />
                    <xs:element ref="InvoiceDate" />
                    <xs:element ref="PurchaseType" />
                    <xs:element ref="SupplierID" />
                    <xs:element name="DocumentTotals">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="TaxPayable" />
                          <xs:element ref="NetTotal" />
                          <xs:element ref="GrossTotal" />
                          <xs:group ref="DeductibleTaxes" minOccurs="0"  maxOccurs="unbounded" />
                          <xs:element minOccurs="0" name="Currency" type="Currency" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="WithholdingTax" type="WithholdingTax">
                      <xs:annotation>
                        <xs:documentation>Informação relativa a impostos retidos pelo fornecedor.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

**Comment by cryptolopes** [comment]
ver (#65 e #20)
