### ISSUE TITLE
Dificuldade em validar as hash

### ISSUE THREAD

**Issue by Stefano-Lorenzo** [assoft-portugal/SAF-T-AO#104]
Boas caríssimos,

Tenho dificuldades na validação das hash.

1ª assinatura:
2020-10-27;2020-10-27T20:32:13;OR 6ALL2020/1;67500.00; 

hash: ZA5DkeKJ6y9OOwhZB+nqiXHXkPvlDYepgX53a00B3XmkV6WwaZy5fegDvM8A6xk9es/W8k8IpYimRC5GRQznHP9e/LKV9pGLMejszuw7UCZ2QRuz4mUrOJTYXqWYNYqTK9BV2KTIwqtV8ibivx/2oIQn6AsH7iDdvy2uxb1V7+w=

2ª assinatura:
2020-10-27;2020-10-27T20:32:49;OR 6ALL2020/2;95760.00;ZA5DkeKJ6y9OOwhZB+nqiXHXkPvlDYepgX53a00B3XmkV6WwaZy5fegDvM8A6xk9es/W8k8IpYimRC5GRQznHP9e/LKV9pGLMejszuw7UCZ2QRuz4mUrOJTYXqWYNYqTK9BV2KTIwqtV8ibivx/2oIQn6AsH7iDdvy2uxb1V7+w=

hash:
KU8tdvO0tgm0kVN82YiAbztQNsMEovGl4vLBBnxuQCRJSJJbJTI1ZEo8K9U5DHZi8YoBgfddEgRTRhKAnMS9GAuousvsSpYq8JQMOp4h4TDNQt+AfC2VMNgWNfLmzjhoZ39vK4+Im+Uo9Jo/oQ4FfNQZCzaEthiyz1FJEBNn+6o=

![Capturar2](https://user-images.githubusercontent.com/65769769/97361254-8d095d80-189f-11eb-969e-62980212e9cc.PNG)

[ChavePublica.txt](https://github.com/assoft-portugal/SAF-T-AO/files/5448103/ChavePublica.txt)

_Originally posted by @Stefano-Lorenzo in https://github.com/assoft-portugal/SAF-T-AO/issues/49#issuecomment-717535986_

**Comment by Marcosinffoco** [comment]
Stefano,

Já existe resolução para este assunto.  Procure nos assuntos validação chave hash . 
Vai encontrar muitas coisas, pois passei por isto.

Tem que verificar tudo..  no saft.   o gross total, net total, tax ,  todos os valores do documento delcarado.   a data de emissão, pois o validador compara tudo com a sua chave gerada.

Procure.  Existe muitos assuntos sobre isto.

Outro assunto,   espere que a sua chave publica seja de testes.   E não de produção.

Isto é perigoso deixar aqui publico para todos verem a sua chave publica.  Tem de proteger isto.

Inté

Marcos

**Comment by Stefano-Lorenzo** [comment]
> Stefano,
> 
> Já existe resolução para este assunto. Procure nos assuntos validação chave hash .
> Vai encontrar muitas coisas, pois passei por isto.
> 
> Tem que verificar tudo.. no saft. o gross total, net total, tax , todos os valores do documento delcarado. a data de emissão, pois o validador compara tudo com a sua chave gerada.
> 
> Procure. Existe muitos assuntos sobre isto.
> 
> Outro assunto, espere que a sua chave publica seja de testes. E não de produção.
> 
> Isto é perigoso deixar aqui publico para todos verem a sua chave publica. Tem de proteger isto.
> 
> Inté
> 
> Marcos

Ok Marcos, muito obrigado, embora eu já tenha checado tudo e feito o teste directamente pelo openssl mas vou seguir a sua dica e o conselho sobre a chave

**Comment by cryptolopes** [comment]
- [Pesquisar a solução em Issues fechados](https://github.com/assoft-portugal/SAF-T-AO/issues?q=Hash)

Alguns exemplos: #96 #88 #78 #67 #63 #58 #49 #46
