### ISSUE TITLE
TaxExemptionReason está mal preenchido.

### ISSUE THREAD

**Issue by AugCri** [assoft-portugal/SAF-T-AO#105]
Saudações, ilustres.

Até há bem pouco tempo, estava tudo bem. Mas agora recebo o seguinte erro:

**TaxExemptionReason está mal preenchido.**

Por favor, preciso de ajuda.

O que será? O que foi alterado?

` <Tax>`
    `<TaxType>IVA</TaxType>`
    `<TaxCountryRegion>AO</TaxCountryRegion>`
    `<TaxCode>ISE</TaxCode>`
    `<TaxPercentage>0.00</TaxPercentage>`
`</Tax>`
`<TaxExemptionReason>Isento nos termos da alínea d) do nº 1 do artigo 12º do CIVA</TaxExemptionReason>`
`<TaxExemptionCode>M13</TaxExemptionCode>`
`<SettlementAmount>0.00</SettlementAmount>`
               
Vi algumas informações como [essa](https://github.com/assoft-portugal/SAF-T-AO/search?q=TaxExemptionReason) e essa [aqui](https://github.com/assoft-portugal/SAF-T-AO/issues/101) mas não respondem a minha questão. 

Qual é a expressão que agora deve ser utilizada no TaxExemptionReason, em caso de M13?

Agradecimentos antecipados e reiteradas saudações

**Comment by batalhadematos** [comment]
@AugCri Estimado, depois de alguns testes e tal como descrito aqui acho que pelo Marcolino, o texto em TaxExemptionReason deve estar tal e qual ao texto apresentado no decreto. Pessoalmente utilizo o TaxExemption.json que está no repositório e testei por exemplo o M02 e o M14 com descrições intencionalmente erradas e falharam. Após corrigir o texto, a validação passou sem problemas. Acontece porém que testei o M13 com a descrição que vem nesse json e também falha, mas o problema estará mesmo aí

**Comment by AugCri** [comment]
> @AugCri Estimado, depois de alguns testes e tal como descrito aqui acho que pelo Marcolino, o texto em TaxExemptionReason deve estar tal e qual ao texto apresentado no decreto. Pessoalmente utilizo o TaxExemption.json que está no repositório e testei por exemplo o M02 e o M14 com descrições intencionalmente erradas e falharam. Após corrigir o texto, a validação passou sem problemas. Acontece porém que testei o M13 com a descrição que vem nesse json e também falha, mas o problema estará mesmo aí.
> 
> De acordo com o [TaxExemption.json](https://github.com/assoft-portugal/SAF-T-AO/blob/master/Resources/TaxExemptions.json), os motivos de isenção que falham (texto indicado em TaxExemptionReason) são:
> 
> * M13
> * M15
> * M24
> 
> Os restantes passam todos.

@batalhadematos Ilustre, muito obrigado pela explicação. 
Então, se percebi bem, só nos resta aguardar até que essa situação seja superada. 
Mas para quem pretender validar o Sistema junto da AGT, esse constrangimento não será levado em consideração? Já que se trata de uma situação alheia ao produtor? Será que a AGT está ciente disso?

Abraços e agradecimentos reiterados.

**Comment by batalhadematos** [comment]
Estimado @AugCri,

Eu não tenho detalhes sobre esta mudança e não sei se será efectiva ou não.
Apenas o pessoal técnico da AGT poderá dizer alguma coisa.

Apenas me surgiu o mesmo problema e encontrei esta solução que alguém colocou no grupo.

Como utilizo o TaxExemption.json aqui do repositório, tive o cuidado de testar cada um dos motivos de isenção e os três que refiro acima falham e os restantes passam bem.

Já procurei por uma tabela de motivos de isenção e todas as que encontro têm a mesma descrição para estes 3 motivos.

Se calhar esperar que alguém aqui do grupo possa passar as descrições correctas para estes elementos ou uma tabela actualizada - que funcione!!!.

Abraço

Paulo Matos

**Comment by AugCri** [comment]
> Estimado @AugCri,
> 
> Eu não tenho detalhes sobre esta mudança e não sei se será efectiva ou não.
> Apenas o pessoal técnico da AGT poderá dizer alguma coisa.
> 
> Apenas me surgiu o mesmo problema e encontrei esta solução que alguém colocou no grupo.
> 
> Como utilizo o TaxExemption.json aqui do repositório, tive o cuidado de testar cada um dos motivos de isenção e os três que refiro acima falham e os restantes passam bem.
> 
> Já procurei por uma tabela de motivos de isenção e todas as que encontro têm a mesma descrição para estes 3 motivos.
> 
> Se calhar esperar que alguém aqui do grupo possa passar as descrições correctas para estes elementos ou uma tabela actualizada - que funcione!!!.
> 
> Abraço
> 
> Paulo Matos

Caro @batalhadematos, muito obrigado igualmente pelo esclarecimento. 
Possa ser que se trate de uma dificuldade cuja solução está em curso. Mas ainda assim, vou procurar entrar em contacto com a AGT na próxima semana (entre quinta ou sexta) para tentar saber mais um pouco deles e voltarei para postar a resposta.

Abraços

**Comment by batalhadematos** [comment]
OK @AugCri,
Também aguardo a resposta para estes motivos de isenção.

Quanto ao processo de certificação, esteja calmo.

Não será por aí que a sua certificação poderá falhar. O processo de certificação é feito entre a AGT e o produtor e por isso, para todas as situações existe sempre um argumento - válido ou não é claro!

Eles só nos pregam partidas quando mexem no portal sem avisar, fora isso, são todos boa gente o:)

Contudo, tem meio caminho andado e se utilizar em TaxExemptionReason o texto exactamente como descrito no TaxExemption.json, aqui do repositório, apenas terá que encontrar solução para os 3 que refiro.

Abraço

**Comment by AugCri** [comment]
> OK @AugCri,
> Também aguardo a resposta para estes motivos de isenção.
> 
> Quanto ao processo de certificação, esteja calmo.
> 
> Não será por aí que a sua certificação poderá falhar. O processo de certificação é feito entre a AGT e o produtor e por isso, para todas as situações existe sempre um argumento - válido ou não é claro!
> 
> Eles só nos pregam partidas quando mexem no portal sem avisar, fora isso, são todos boa gente o:)
> 
> Contudo, tem meio caminho andado e se utilizar em TaxExemptionReason o texto exactamente como descrito no TaxExemption.json, aqui do repositório, apenas terá que encontrar solução para os 3 que refiro.
> 
> Abraço

Isso mesmo, caro @batalhadematos.
Obrigado e saudações

**Comment by AugCri** [comment]
Estimados, do nada a situação ficou resolvida. Do nada mesmo porque não fizemos nada (rsrs). Podem utilizar a vontade.

Saudações
