### ISSUE TITLE
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.4Invoice (FT SSGOSGI20/60) não deve conter IVA.

### ISSUE THREAD

**Issue by Hugo-hmdm** [assoft-portugal/SAF-T-AO#108]
Boa tarte,

Ao validar um ficheiro de SAF-T no validador do produtor de software deparámo-nos com o erro "Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.4Invoice (FT SSGOSGI20/60) não deve conter IVA.".
O erro ocorre na presença de uma fatura de cliente estrangeiro. A taxa utilizada é uma taxa de IVA registada com o respetivo motivo de isenção, uma vez que se trata de uma exportação.
Não conseguimos identificar qual poderá ser a razão do erro. 
Avaliámos a estrutura do nosso ficheiro com o schema disponível, e não obtivemos nenhum erro.
Pedimos a vossa ajuda para que possamos descobrir a origem do [mesmo.](url
[ErroTaxas.zip](https://github.com/assoft-portugal/SAF-T-AO/files/5579807/ErroTaxas.zip)
)

Coloco em anexo o ficheiro SAF-T e uma imagem do erro.

**Comment by cryptolopes** [comment]
> Não conseguimos identificar qual poderá ser a razão do erro.

Consiste numa validação orgânica realizada pela AGT.
Pese embora não exista um erro de estrutura, chamo à atenção para o elemento `TaxType` que está preenchido com o valor `IS`, quando na realidade devia ser `IVA`.

Linha 3606

```xml
<Tax>
    <TaxType>IS</TaxType>
    <TaxCountryRegion>AO</TaxCountryRegion>
    <TaxCode>ISE</TaxCode>
    <TaxPercentage>0.00</TaxPercentage>
</Tax>
```

O elemento TaxType tem as seguintes opções:
https://github.com/assoft-portugal/SAF-T-AO/blob/97c7d2006b5037471261e7f8d97e752785fe33f9/XSD%2FSAFTAO1.01_01.xsd#L1624-L1632

**Comment by reactor-gonguela** [comment]
Bom dia ilustres, já experimentei este erro em tempos e a solução parece ser simples. 

Solução: **Sempre que um cliente tem no campo Country um valor diferente de AO** o validador gera este erro, @Hugo-hmdm, a solução passa por substituir o Country code do primeiro cliente no SAFT
![InkedCountry PT_LI](https://user-images.githubusercontent.com/40264322/99937052-faa48e80-2d64-11eb-9562-0afc812e0162.jpg)
. 
`<Customer>
<CustomerID>000004</CustomerID>
<AccountID>31122</AccountID>
<CustomerTaxID>510873758</CustomerTaxID>
<CompanyName>P.S.L Navegação</CompanyName>
<Contact>JOSE\JOSELUIS</Contact>
<BillingAddress>
<BuildingNumber>Incognito</BuildingNumber>
<StreetName>Av. D. Afonso Henriques, 1196 - sala 204</StreetName>
<AddressDetail>Av. D. Afonso Henriques, 1196 - sala 204</AddressDetail>
<City>MATOSINHOS</City>
<PostalCode>4450-012</PostalCode>
<Province>Desconhecido</Province>
<Country>AO</Country>
</BillingAddress>
<Telephone>Desconhecido</Telephone>
<Fax>Desconhecido</Fax>
<Email>Desconhecido</Email>
<Website>Desconhecido</Website>
<SelfBillingIndicator>0</SelfBillingIndicator>
</Customer>`
Questão: é normal o validador agir assim @cryptolopes?

**Comment by RodrigoJeronimo** [comment]
> > Não conseguimos identificar qual poderá ser a razão do erro.
> 
> Consiste numa validação orgânica realizada pela AGT.
> Pese embora não exista um erro de estrutura, chamo à atenção para o elemento `TaxType` que está preenchido com o valor `IS`, quando na realidade devia ser `IVA`.
> 
> Linha 3606
> 
> ```
> <Tax>
>     <TaxType>IS</TaxType>
>     <TaxCountryRegion>AO</TaxCountryRegion>
>     <TaxCode>ISE</TaxCode>
>     <TaxPercentage>0.00</TaxPercentage>
> </Tax>
> ```
> 
> O elemento TaxType tem as seguintes opções:
> https://github.com/assoft-portugal/SAF-T-AO/blob/97c7d2006b5037471261e7f8d97e752785fe33f9/XSD%2FSAFTAO1.01_01.xsd#L1624-L1632

Bom dia Nelson,
O ficheiro SAF-T que está em anexo não contém esse valor na linha 3606.

![image](https://user-images.githubusercontent.com/74905783/99953214-e10d4200-2d78-11eb-841c-130fabe8c055.png)

Deste modo, ficamos a aguardar novos comentários.

Obrigado

**Comment by Hugo-hmdm** [comment]
> Bom dia ilustres, já experimentei este erro em tempos e a solução parece ser simples.
> 
> Solução: **Sempre que um cliente tem no campo Country um valor diferente de AO** o validador gera este erro, @Hugo-hmdm, a solução passa por substituir o Country code do primeiro cliente no SAFT
> ![InkedCountry PT_LI](https://user-images.githubusercontent.com/40264322/99937052-faa48e80-2d64-11eb-9562-0afc812e0162.jpg)
> .
> `<Customer> <CustomerID>000004</CustomerID> <AccountID>31122</AccountID> <CustomerTaxID>510873758</CustomerTaxID> <CompanyName>P.S.L Navegação</CompanyName> <Contact>JOSE\JOSELUIS</Contact> <BillingAddress> <BuildingNumber>Incognito</BuildingNumber> <StreetName>Av. D. Afonso Henriques, 1196 - sala 204</StreetName> <AddressDetail>Av. D. Afonso Henriques, 1196 - sala 204</AddressDetail> <City>MATOSINHOS</City> <PostalCode>4450-012</PostalCode> <Province>Desconhecido</Province> <Country>AO</Country> </BillingAddress> <Telephone>Desconhecido</Telephone> <Fax>Desconhecido</Fax> <Email>Desconhecido</Email> <Website>Desconhecido</Website> <SelfBillingIndicator>0</SelfBillingIndicator> </Customer>`
> Questão: é normal o validador agir assim @cryptolopes?

Bom dia @reactor-gonguela ,

De facto se alterarmos o country code do primeiro cliente já não obtemos o erro. Muito obrigado pela ajuda.
@cryptolopes esta validação por parte da AGT está correta?

Obrigado.

**Comment by cryptolopes** [comment]
@Hugo-hmdm Não. Isso carece de correção pela AGT. Vou organizar a documentação aqui para expor o problema à AGT.

**Comment by Hugo-hmdm** [comment]
> Isso carece de correção pela AGT. Vou organizar a documentação aqui para expor

@cryptolopes Muito obrigado pela resposta.

**Comment by cryptolopes** [comment]
> O ficheiro SAF-T que está em anexo não contém esse valor na linha 3606.

```xml
<InvoiceNo>FT SSGOSGI20/60</InvoiceNo>
<!-- ... -->
 <Tax>
    <TaxType>IS</TaxType>
    <TaxCountryRegion>AO</TaxCountryRegion>
    <TaxCode>ISE</TaxCode>
    <TaxPercentage>0.00</TaxPercentage>
</Tax>
```

**Comment by batalhadematos** [comment]
> 
> 
> > O ficheiro SAF-T que está em anexo não contém esse valor na linha 3606.
> 
> ```
> <InvoiceNo>FT SSGOSGI20/60</InvoiceNo>
> 
>  <Tax>
>     <TaxType>IS</TaxType>
>     <TaxCountryRegion>AO</TaxCountryRegion>
>     <TaxCode>ISE</TaxCode>
>     <TaxPercentage>0.00</TaxPercentage>
> </Tax>
> ```
> 
> Alterando o `TaxType` para `IVA` o problema desaparece @Hugo-hmdm ?

Viva @cryptolopes 

Testei esta situação e confirmo que o problema se mantém para o problema reportado. 

É gerado o erro "AuditFile.SourceDocuments.SalesInvoices.XInvoice (FT XXXXXX/XX) não deve conter IVA.", quando se emite uma factura para um cliente estrangeiro, com o nó acima corrigido (IVA ao invés de IS no TaxType).

Abraço
