### ISSUE TITLE
Erro ao validar xml - SupplierCountry

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#11]
Bom dia,

experimentei validar um simples ficheiro saft e ocorre o erro que se encontra na imagem que está em anexo.

Penso que o problema esteja no tipo "SupplierCountry" (linha 1832 do xsd) mas não consigo perceber qual é a causa problema.

![Erro_Validar_Saft](https://user-images.githubusercontent.com/53896958/62696896-61b3fd80-b9d1-11e9-952a-fe68c412eb1f.PNG)

Para validar usei o software NotePad ++ e a última versão do xsd.

Deixo um link para download do ficheiro saft que usei.
https://we.tl/t-ekc3cjub2c 

Cumprimentos,

Miguel Silva

**Comment by cryptolopes** [comment]
Olá @MiguelSilva-PBSS 
Creio que o problema estava [aqui](https://github.com/assoft-portugal/SAF-T-AO/commit/2ee5f460d7b5879d3de9971a88289b739adb7105).
Teste novamente com o XSD que está em DEV https://github.com/assoft-portugal/SAF-T-AO/blob/dev/XSD/SAFTAO1.01_01.xsd

**Comment by MiguelSilva-PBSS** [comment]
Está resolvido! Obrigado.

**Comment by cryptolopes** [comment]
Na próxima [Release](https://github.com/assoft-portugal/SAF-T-AO/releases) já estará resolvido. Até lá, peço que acompanhe o este branch.
