### ISSUE TITLE
MovementOfGoods sem/com CreditAmount

### ISSUE THREAD

**Issue by jleal-grupopie** [assoft-portugal/SAF-T-AO#110]
Pelo _Decreto Executivo n.º 317/20_, as linhas dos MovementOfGoods deixam de ter CreditAmount.
* 4.2.3.21.11. Valor a crédito (CreditAmount).

O elemento acima deixou de estar documentado.
Devemos ignorar e continuar a usar CreditAmount e DebitAmount?

**Comment by cryptolopes** [comment]
Claramente um lapso.
Há inclusive um salto na numeração dos elementos.
