### ISSUE TITLE
"Guia de Consignação" sai da tabela MovementOfGoods?

### ISSUE THREAD

**Issue by jleal-grupopie** [assoft-portugal/SAF-T-AO#111]
Pelo Decreto Executivo n.º 317/20, as **Guia de Consignação** deixam de fazer parte dos `MovementOfGoods` e passam para os `WorkingDocuments`. No entanto, continuam a fazer parte do schema.
Devem continuar a ser exportadas **Guias de Consignação** nos `MovementOfGoods`?

**MovementOfGoods:**
> **4.2.3.8. - Tipo de documento (MovementType):**
> Deve ser preenchido com:
> * GR – Guia de remessa;
> * GT – Guia de transporte (incluir aqui as guias globais);
> * GA – Guia de movimentação de activos fixos próprios;
> * GD – Guia ou nota de devolução.

**WorkingDocuments:**
> **4.3.4.8. - Tipo de documento (WorkType):**
> Deve ser preenchido com:
> * CM – Consultas de mesa;
> * GC – Guia de Consignação;
> * GR – Guia de remessa;
> * NR – Nota de remessa;
> * FO – Folhas de obra;
> * NE – Nota de Encomenda;
> * OU – Outros;
> * OR – Orçamentos;
> * PP – Pró-forma;
> * DC – Documentos emitidos que sejam susceptíveis de apresentação ao cliente para conferência de mercadorias ou de prestação de serviços.
> Para o sector Segurador quando para os tipos de documentos a seguir identificados também deva existir na tabela 4.1 - Documentos comerciais a clientes (SalesInvoices) a correspondente factura ou documento rectificativo de factura, ainda pode ser preenchido com:
> * RP – Prémio ou recibo de prémio;
> * RE – Estorno ou recibo de estorno;
> * CS – Imputação a co-seguradoras;
> * LD – Imputação a co-seguradora líder;
> * RA – Resseguro aceite.

___

**SCHEMA:**

**MovementOfGoods:**
```xml
  <!-- Tipo de documento de movimentacao de mercadorias-->
  <xs:element name="MovementType">
    <xs:annotation>
      <xs:documentation>
          Deve ser preenchido com:
          “GR” – Guia de remessa;
          “GT” – Guia de transporte (incluir aqui as guias globais);
          “GA” – Guia de movimentação de activos fixos próprios; 
          “GC” – Guia de consignação;
          “GD” – Guia ou nota de devolução. 
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="GR" />
        <xs:enumeration value="GT" />
        <xs:enumeration value="GA" />
        <xs:enumeration value="GD" />
        <xs:enumeration value="GC" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
```

**WorkingDocuments:**
```xml
  <xs:element name="WorkType">
    <xs:annotation>
      <xs:documentation>
          Deve ser preenchido com:
          “CM” – Consultas de mesa;
          “CC” – Credito de consignação;
          “GR” – Guia de remessa;
          “NR” – Nota de remessa;
          “FO” – Folhas de obra;
          “NE” – Nota de Encomenda;
          “OU” – Outros;
          “OR” – Orçamentos;
          “PF” – Pró-forma;
          “DC” – Documentos emitidos que sejam susceptíveis de apresentação ao cliente para conferência de mercadorias ou de prestação de serviços. Para o sector Segurador quando para os tipos de documentos a seguir identificados também deva existir na tabela 4.1 - Documentos comerciais a clientes (SalesInvoices) a correspondente factura ou documento rectificativo de factura, ainda pode ser preenchido com:
          “RP” – Prémio ou recibo de prémio;
          “RE” – Estorno ou recibo de estorno;
          “CS” – Imputação a co-seguradoras; “LD” – Imputação a co-seguradora líder; “RA” – Resseguro aceite.
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="CM" />
        <xs:enumeration value="CC" />
        <xs:enumeration value="GR" />
        <xs:enumeration value="NR" />
        <xs:enumeration value="FO" />
        <xs:enumeration value="NE" />
        <xs:enumeration value="OU" />
        <xs:enumeration value="OR" />
        <xs:enumeration value="PF" />
        <xs:enumeration value="DC" />
        <xs:enumeration value="RP" />
        <xs:enumeration value="RE" />
        <xs:enumeration value="CS" />
        <xs:enumeration value="LD" />
        <xs:enumeration value="RA" />
        <xs:enumeration value="PP" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
```

**Comment by jleal-grupopie** [comment]
> 
> 
> > O decreto executivo 317/20 de 14 de Dezembro, que altera a emissão do SAFT AO, nomeadamente para a tabela 4.3,  relativa aos documentos de conferencia de entrega de mercadoria ou da prestação de serviços,
> > [View in Slack](https://assoft.slack.com/archives/C01ACBKFUHK/p1611690902006700)
> 
> Deixa de ter suporte a `PF`.

No _Decreto Presidencial n.º312/18_ o documento **Pro-Forma** já estava como `PP` e não como `PF`.
Possivelmente estavam a suportar os dois códigos.

A duvida aqui são as **Guias de consignação** (`GC`), dado que no _Decreto Executivo n.º 317/20_ tem a passagem deste documento do nó `MovementOfGoods` para o `WorkingDocuments`, que não é suportada pelo schema nem pelo validador da AGT.

**Comment by cryptolopes** [comment]
Sim, juntei aquela a este issue porque tem que ver com o mesmo trabalho de revisão do nova legislação.
