### ISSUE TITLE
Acerca do Hash na integração de documentos manuais

### ISSUE THREAD

**Issue by AfonsoMenata** [assoft-portugal/SAF-T-AO#117]
Bom dia, pessoal. Preciso uma vez mais de vossa ajuda!

Para criar a assinatura de um documento emitido manualmente e integrado na aplicação, deve-seadicionar uma informação:
1-FTM ab/001, neste formato. Segundo o ponto 8 dos requisitos de validaçãom alínea e).

A minha questão é, onde adicionar essa informação no hassh?? Concatenando, com ";" antes??

Agredeço a vossa apreciação.

**Comment by cryptolopes** [comment]
@AfonsoMenata Podes carregar os requisitos para aqui?

**Comment by AfonsoMenata** [comment]
@cryptolopes. Está em pdf, não consigo anexar. Trata-se do decreto presidencial que fala sobre os rquisitos de validação dos softwares.

**Comment by AfonsoMenata** [comment]
@cryptolopes.
http://www.ucm.minfin.gov.ao/cs/groups/public/documents/document/zmlu/mdu1/~edisp/minfin055809.pdf
