### ISSUE TITLE
Erro na validalição do WithholdingTaxType

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#123]
Boa tarde,

ao validar um ficheiro SAF-T contra o .xsd, ocorre um erro no WithholdingTaxType, mais especificamente quando usamos os WithholdingTaxType "OU" e "IAC".

ERROR: Element '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}WithholdingTaxType': [facet 'enumeration'] The value 'OU' is not an element of the set {'IRT', 'II', 'IS', 'IVA', 'IPU'}.

Achamos que está a faltar estes dois tipos no xsd.

**Comment by cryptolopes** [comment]
> Achamos que está a faltar estes dois tipos no xsd.

Obrigado pelo feedback.
