### ISSUE TITLE
Existem erros de sintaxe xml no ficheiro (Falha validação xsd)

### ISSUE THREAD

**Issue by softwareangola** [assoft-portugal/SAF-T-AO#129]
Bom dia,

Consegui importar o SAFT de Janeiro 2021 com sucesso, os ficheiros de Maio a Dezembro 2020 recebo a mensagem do portal "Existem erros de sintaxe xml no ficheiro (Falha validação xsd)"

Alguma solução a vista?

<?xml version="1.0" encoding="Windows-1252"?>
<AuditFile xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01">

**Comment by cryptolopes** [comment]
@softwareangola O encoding do SAF-T (AO) é UTF-8, mas isso não deveria ser um problema.
Validou o XML contra o schema?

**Comment by softwareangola** [comment]
@cryptolopes boa tarde,

problema estava aqui <ProductDescription>SANEX MEN **ZERO**</ProductDescription>
				<ProductNumberCode>8718951068407</ProductNumberCode>

Obrigado
