### ISSUE TITLE
Na tabela de Produtos - UNNumber

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#13]
Boa tarde,

ao validar o ficheiro com a última versão, ocorre um erro na tabela de produtos se antes do campo UNNumber não estiver preenchido o campo CustomDetails.

Segundo o Decreto Presidencial, o campo CustomDetails não é de preenchimento obrigatório.

![UNNumber](https://user-images.githubusercontent.com/53896958/62722491-68a93300-ba06-11e9-93f5-e6e2c131c7ca.png)

Cumprimentos,

Miguel Silva.

**Comment by cryptolopes** [comment]
Olá @MiguelSilva-PBSS 
Após confirmar com a AGT a estrutura que está no XSD está correta.
Efetivamente a numeração dos campos pode dar a entender que são elementos independentes, mas na realidade o elemento UNNumber deve constar como um sub-elemento de CustomsDetails.
