### ISSUE TITLE
"2.4.6.1.-UNNumber" ficaria inserido sob o nó "2.4.6.-CustomsDetails"?

### ISSUE THREAD

**Issue by Schobert** [assoft-portugal/SAF-T-AO#135]
Segundo 317/2020, o campo "**2.4.6.1. UNNumber**", tal como descrito neste Decreto, ficaria inserido sob o nó "**2.4.6.-CustomsDetails**".
Isso é uma alteração à estrutura, visto que antes este campo ficava fora dessa estrutura, (2.4.7.	UNNumber).
Isso é um erro do texto da lei ou está correto?

Obrigada pela ajuda.

-- | --

-- | --

**Comment by cryptolopes** [comment]
Possivelmente,
A versão atual do schema já contempla o `UNNumber` como um subelemento de `CustomsDetails`.

https://github.com/assoft-portugal/SAF-T-AO/blob/1737f347e65a607a0c7fb136a31e8d7787d94e42/XSD/SAFTAO1.01_01.xsd#L253-L264

**Comment by Schobert** [comment]
Thank you!
