### ISSUE TITLE
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.445Invoice.1Line.TaxExemptionReason está mal preenchido

### ISSUE THREAD

**Issue by AugCri** [assoft-portugal/SAF-T-AO#142]
Bom dia, caríssimos.
ERRO: Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.445Invoice.1Line.TaxExemptionReason

Alguém pode me dizer, por favor, como é que se preenche o "IVA - Regime Simplificado"?

Por qual motivo esse erro persiste, caríssimos?
Já vi outros links aqui mas não me explicam algo diferente.
Por favor, alguém me pode dizer o que está errado? Alguém já passou por isso? Ou há um problema com o portal da AGT?

Muito obrigado
![IMAGEM_ERRO_SAFT_AO](https://user-images.githubusercontent.com/72359553/110203360-10e6de00-7e6e-11eb-831b-2582cbb4759e.png)

**Comment by cryptolopes** [comment]
Duplicate of #140
