### ISSUE TITLE
O campo AuditFile.SourceDocuments.PurchaseInvoices.Invoice.DocumentTotals.DeductibleTaxes no ficheiro está na posição errada

### ISSUE THREAD

**Issue by diogoscmartins** [assoft-portugal/SAF-T-AO#149]
Boas,

Estou a ter um problema ao validar o ficheiro SAFT no validador da AGT, e não estou a conseguir encontrar a causa.

Está a dar o seguinte erro:

O campo AuditFile.SourceDocuments.PurchaseInvoices.Invoice.DocumentTotals.DeductibleTaxes no ficheiro está na posição errada.

A estrutura que estou a usar envio na imagem abaixo.

![image](https://user-images.githubusercontent.com/81979886/113595591-1aac5e80-9631-11eb-841f-6007048ce25d.png)

Cumprimentos,
Diogo Martins

**Comment by cryptolopes** [comment]
> https://github.com/assoft-portugal/SAF-T-AO/discussions/148#discussioncomment-530701

**Comment by diogoscmartins** [comment]
Obrigado pela resposta imediata.
