### ISSUE TITLE
Falha na validação, a informação AuditFile.Header.SoftwareValidationNumber não está conforme com a do programa validado

### ISSUE THREAD

**Issue by AlfredoFerreirahr** [assoft-portugal/SAF-T-AO#152]
Falha na validação, a informação AuditFile.Header.SoftwareValidationNumber não está conforme com a do programa validado

**Comment by AlfredoFerreirahr** [comment]
viva caríssimos, alguém pode ajudar com este erro ao importar saft AGT Angola?

**Comment by cryptolopes** [comment]
Duplicate of #45 

mais informação em #30
