### ISSUE TITLE
Settlement, Payment e WithholdingTax em SalesInvoices

### ISSUE THREAD

**Issue by cryptolopes** [assoft-portugal/SAF-T-AO#157]
O Decreto Presidencial 317/20 não menciona o subconjunto de elementos `Settlement`, `Payment` e `WithholdingTax` na estrutura `SalesInvoices`.

https://github.com/assoft-portugal/SAF-T-AO/blob/6656f9d80b50262bd24d2f1518c0b43cf42dcc00/XSD/SAFTAO1.01_01.xsd#L511-L526

Terá sido um lapso?

**Comment by Schobert** [comment]
O 4.1.4.20.6 - Payment efetivamente foi eliminado (e ainda bem :) ).

No entanto, WithholdingTax e Settlement estão lá no decreto:
4.1.4.21 - WithholdingTax
4.1.4.20.5 - Settlement
ou percebi mal o teu comentário?

**Comment by cryptolopes** [comment]
@Schobert Talvez tenha visto mal. 🤭
