### ISSUE TITLE
Erro na comunicação de Guias à Consignação - Não permite entrega no MovementsOfGoods nem no WorkingDocuments

### ISSUE THREAD

**Issue by patricialmeida** [assoft-portugal/SAF-T-AO#158]
Na entrega do ficheiro SAFT-AO, deu erro nas guias à consignação no passado dia 30 de Abril de 2021.

Temos um cliente em Angola que emitiu guias à consignação no mês passado e à luz do Decreto Presidencial 371/20 alteramos  o documento "GC" dos MovementsOfGoods, para os WorkingDocumentos.

Ao entregar o SAFT na sexta feira, estava a dar nestes documentos o seguinte erro:

**“Preenchimento errado, o campo AuditFile.SourceDocuments.WorkingDocuments.3WorkDocument.WorkType (GC VG2021NUT/1) só deve ser preenchido com (CM,CC,GR,NR,FO,NE,OU,OR,PP,DC,RP,RE,CS,LD,RA)”**

Tentando entregar estes documentos ao abrigo da legislação anterior também não permitiu dando o erro:
**Preenchimento errado, o campo AuditFile.SourceDocuments.MovementOfGoods.241StockMovement.MovementType (GC VG2021NUT/1) só deve ser preenchido com (GR,GT,GA,GD)"**

Este documento deve ser entregue em que grupo e com que tipo de documento?

**Comment by cryptolopes** [comment]
Esta alteração já está contemplada no PR #133. 
Também foi comentada em #111.
