### ISSUE TITLE
Erro ! DocumentTotals.GrossTotal é maior que o documento de origem.

### ISSUE THREAD

**Issue by inmx** [assoft-portugal/SAF-T-AO#165]
Alguém passando por isso? 
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.1Invoice (FR FR2021/218) .DocumentTotals.GrossTotal é maior que o documento de origem.
Como ultrapassar?

**Comment by cryptolopes** [comment]
https://github.com/assoft-portugal/SAF-T-AO/discussions/162#discussioncomment-698709
