### ISSUE TITLE
Falha no validador da  AGT - TaxPayable

### ISSUE THREAD

**Issue by rafsilva19** [assoft-portugal/SAF-T-AO#17]
Após validar o ficheiro SAFT com o XSD, tentei utilizar o validador da AGT e recebi a seguinte mensagem:

"Falha na validação, porque o TaxPayable do AuditFile.SourceDocuments.SalesInvoices.5Invoice está mal calculado"

Os valores parecem estar iguais aos calculados pelo ficheiro Excel enviado pelo AGT para testes.

[SAFT_20190801_20190930_201909061122.txt](https://github.com/assoft-portugal/SAF-T-AO/files/3583662/SAFT_20190801_20190930_201909061122.txt)

**Comment by cryptolopes** [comment]
Validando contra o XSD está OK!
Reparei que as linhas não estão numeradas de forma correta.
Por exemplo em:
 > /AuditFile/SourceDocuments/SalesInvoices/Invoice[5]/Line/LineNumber
 
 que só tem uma linha, está marcado como sendo a segunda (2) linha.

 ```xml
  <Line>
        <LineNumber>2</LineNumber>
        <ProductCode>1</ProductCode>
        <ProductDescription>Produto 1<ProductDescription>
        <Quantity>1.00</Quantity>
        <UnitOfMeasure>UN</UnitOfMeasure>
        <UnitPrice>10.0000</UnitPrice>
        <TaxBase>10.0000</TaxBase>
        <TaxPointDate>2019-09-06</TaxPointDate>
        <Description>Produto 1</Description>
        <CreditAmount>10.0000</CreditAmount>
        <Tax>
            <TaxType>IVA</TaxType>
            <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>NOR</TaxCode>
            <TaxPercentage>14.0000</TaxPercentage>
        </Tax>
        <SettlementAmount>0.0000</SettlementAmount>
</Line> 
 ```

**Comment by rafsilva19** [comment]
Já corrigi essa questão, mas o erro persiste.

[SAFT_20190801_20190930_201909061408_v2.txt](https://github.com/assoft-portugal/SAF-T-AO/files/3584045/SAFT_20190801_20190930_201909061408_v2.txt)

**Comment by cryptolopes** [comment]
Tente, por favor, fazer o teste apenas com duas casas decimais.
```xml
<TaxPercentage>14.00</TaxPercentage>
```
É apenas para confirmar um aspeto.

**Comment by rafsilva19** [comment]
Fiz a experiência apenas com duas casas, e apenas com o número inteiro. 

A mensagem de erro continuar a aparecer.

**Comment by sfcgomes** [comment]
Podem-me p.f. fornecer o link para o validador da AGT?
