### ISSUE TITLE
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.3Invoice (FT FA.2020/2) .DocumentTotals.GrossTotal é maior que o documento de origem.

### ISSUE THREAD

**Issue by sebastiaopaulo39** [assoft-portugal/SAF-T-AO#172]
Mais Alguém teve esse erro?

Estou tento esse erro em todas as faturas que eu faço, mesmo quando recorro aos safts anteriores que eu sei que já funcionavam sem problema nenhum, mas por algum motivo, todos eles apresetam esse  erro ".DocumentTotals.GrossTotal é maior que o documento"

**Comment by cryptolopes** [comment]
Duplicate of #162
