### ISSUE TITLE
Tamanho do campo CompanyID e BusinessName

### ISSUE THREAD

**Issue by Helkyd** [assoft-portugal/SAF-T-AO#184]
Com base nestes erros:
(1)Número de caracteres errado do campo AuditFile.Header.CompanyID
AuditFile.Header.CompanyID
(2)Número de caracteres errado do campo AuditFile.Header.BusinessName
AuditFile.Header.BusinessName

Muitas das Empresas em Angola tem nomes de Registo muito compridos.. ultrapassam os 50 caracteres.
Se o CompanyID e BusincessName for com base no nome que o cliente forneceu na altura do registo do Software ou mesmo que o Produtor vá consultar na pagina da https://agt.minfin.gov.ao/PortalAGT/#!/servicos/consultar-nif o resultado poderá ser um nome com mais de 50 caracteres.

Assim sendo e vendo que a consulta online retorna os nomes do Registo Comercial correcto acho que o tamanho aqui no SAFT deveria para estes dois campos ser de 80 ou até mesmo 100 caracteres.

Obrigado.

**Comment by cryptolopes** [comment]
Para o efeito não é o elemento `CompanyName` que importa? Esse tem um limite de 200 caractéres.
