### ISSUE TITLE
ExchangeRate - Sales Invoice

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#19]
Bom dia,

ao validar o ficheiro SAF-T de Faturação no validador que existe no site da AGT, devolve um erro no campo ExchangeRate.
_"Formato errado do AuditFile.SourceDocuments.SalesInvoices.1Invoice.DocumentTotals.Currency.ExchangeRate"_

Tenho um valor com mais de 4 casas décimais. Caso altere para 4 casas décimais já não ocorre o erro.

Podem pf confirmar qual é o limite máximo de casas décimais para este campo?

![ExchangeRate](https://user-images.githubusercontent.com/53896958/65137076-9b304d80-da00-11e9-9e85-24ac8d50b4ae.PNG)

**Comment by cryptolopes** [comment]
Olá @MiguelSilva-PBSS 

```xml
  <xs:simpleType name="SAFdecimalType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.00" />
    </xs:restriction>
  </xs:simpleType>
```

O elemento não tem limite de casas decimais. É uma verificação própria do validador da AGT.
