### ISSUE TITLE
AuditFile.SourceDocuments.Payments.Payment.Line.SourceDocumentID.OriginatingON  não permite repetição

### ISSUE THREAD

**Issue by Schobert** [assoft-portugal/SAF-T-AO#192]
**AuditFile.SourceDocuments.Payments.Payment.Line.SourceDocumentID.OriginatingON** não permite repetições

Nos pagamentos, quando há mais do que uma ocorrência de OriginatingON, dá erro na submissão do ficheiro. Especificamente neste caso há duas faturas para o mesmo pagamento. Existem portanto duas entradas OriginatingON (uma por cada fatura). No XSD, OriginatingON está definido com Unbound, deveria portanto ser repetível.

<Line>
    <LineNumber>000001</LineNumber>
    <SourceDocumentID>
          <OriginatingON>FT F2AO12&62021/1019669803</OriginatingON>                        
          <InvoiceDate>2021-09-10</InvoiceDate>
          <OriginatingON>FT F2AO12&62021/1019669813</OriginatingON>               
          <InvoiceDate>2021-09-11</InvoiceDate>
    </SourceDocumentID>
    <CreditAmount>.......

Está errado? Se sim, como deve ser?
Até agora nunca tinha tido mensagem de erro, para mim é novidade.

Obrigada, Daniela Schobert

**Comment by cryptolopes** [comment]
> No XSD, OriginatingON está definido com Unbound, deveria portanto ser repetível.

E é repetível.
É algo que a AGT deve rever do seu lado.

```xml
<xs:element maxOccurs="unbounded" name="SourceDocumentID">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="OriginatingON" />
      <xs:element ref="InvoiceDate" />
      <xs:element minOccurs="0" ref="Description" />
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

**Comment by Schobert** [comment]
Obrigada Nelson. é o que também penso. vou insistir com a AGT.

**Comment by Schobert** [comment]
Example for the correct structure:

<Line>
<LineNumber>000001</LineNumber>
**<SourceDocumentID>**
<OriginatingON>FT ZNIVAO13&amp;Z2021/1025066315</OriginatingON>
<InvoiceDate>2021-08-24</InvoiceDate>
**</SourceDocumentID>**
**<SourceDocumentID>**
<OriginatingON>FT ZNIVAO13&amp;Z2021/1025066329</OriginatingON>
<InvoiceDate>2021-09-14</InvoiceDate>
**</SourceDocumentID>**
<CreditAmount>313583458.0000000</CreditAmount>
<Tax>
<TaxType>IVA</TaxType>
<TaxCountryRegion>AO</TaxCountryRegion>
<TaxCode>NOR</TaxCode>
<TaxPercentage>5.00</TaxPercentage>
</Tax>
</Line>



Daniela
