### ISSUE TITLE
Erro ao Validar o SAF-T de Aquisições Bens e Serviços

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#20]
Boa tarde,

ao validar o ficheiro SAF-T de Aquisições Bens e Serviços (TaxAccountingBasis = A) com a última versão do .xsd ocorre o seguinte erro:

ERROR: Element '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}Invoices': This element is not expected. Expected is one of ( {urn:OECD:StandardAuditFile-Tax:AO_1.01_01}GeneralLedgerEntries, {urn:OECD:StandardAuditFile-Tax:AO_1.01_01}SourceDocuments ).

No Decreto Presidencial não está previsto as tabelas "GeneralLedgerEntries" e "SourceDocuments" mas sim só a tabela "Invoices".

![Erro SourceDocuments2](https://user-images.githubusercontent.com/53896958/65242594-511d9980-dade-11e9-91ca-741126c30083.PNG)

![Erro SourceDocuments](https://user-images.githubusercontent.com/53896958/65242725-b1acd680-dade-11e9-8ddb-8d2c84716a99.PNG)

Cumprimentos.

**Comment by cryptolopes** [comment]
Olá,
Essa parte da estrutura foi alterada entretanto, pese embora ainda não esteja vertido na Lei. Será ainda objeto de nova modificação, segundo as indicações da AGT.

**Comment by sgouveia2919** [comment]
Estou a desenvolver o ficheiro de Aquisição de Bens e Serviços. Submeti o ficheiro gerado ao XSD disponibilizado (SAFTAO1.01_01.xsd) e passou com sucesso, corrigindo a questão do padrão obrigatório para o InvoiceNo.
Ao submeter no Portal das Finanças de Angola dá erros.
A parte do ficheiro relativo aos Documentos comerciais de Fornecedores (Invoice)


![image](https://user-images.githubusercontent.com/58046611/69365366-17a70d00-0c8c-11ea-80c7-8ab18e3b6fb5.png)

Os erros que ocorrem no portal:

O nóAuditFile.SourceDocuments.PurchaseInvoices.InvoiceNo no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.Period no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.InvoiceDate no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.InvoiceType no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.SourceID no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.SupplierID no arquivo não deve existir.
O nóAuditFile.SourceDocuments.PurchaseInvoices.Invoice no arquivo não deve existir.

Alguém pode ajudar a despistar este erro?
Aparentemente não espera estes campos na SourceDocuments.PurchaseInvoices.

**Comment by cryptolopes** [comment]
> Alguém pode ajudar a despistar este erro?
> Aparentemente não espera estes campos na SourceDocuments.PurchaseInvoices.

O Validador no Portal da AGT ainda não está a testar o schema para esse efeito.

**Comment by sgouveia2919** [comment]
Boa tarde, 

Já há previsão para que o Validador no Portal da AGT considere este ficheiro?
Ainda hoje validei um ficheiro e os erros persistem.

Grata, 
Sandra Gouveia

**Comment by cryptolopes** [comment]
> Já há previsão para que o Validador no Portal da AGT considere este ficheiro?

Todos esperamos que seja para breve.

**Comment by sgouveia2919** [comment]
> > Já há previsão para que o Validador no Portal da AGT considere este ficheiro?
> 
> Todos esperamos que seja para breve.

Obrigada pela pronta resposta!

**Comment by MiguelSilva-PBSS** [comment]
Não podemos esquecer que antes da atualização do validador é preciso que seja aprovado um decreto presidencial com estas alterações.

**Comment by cryptolopes** [comment]
# Proposta de alteração da estrutura PurchaseInvoices

## Tabela com elementos da estrutura

| Índice do campo 	| Obrigatório 	| Nome do campo                                                   	| Notas técnicas                                                                                                                                                                                                                                                                                                                         	|    Formato    	|
|-----------------	|:-----------:	|-----------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|:-------------:	|
| 4.5             	|             	| Documentos comerciais a fornecedores (PurchaseInvoices)         	| Devem ser exportados os documentos indicados no campo 4.5.2.6 - Tipo de documento (PurchaseType)                                                                                                                                                                                                                                       	| não aplicável 	|
| 4.5.1           	|      *      	| Número de registos de documentos comerciais (NumberOfEntries)   	| Deve conter o número total de documentos incluídos.                                                                                                                                                                                                                                                                                    	|    Inteiro    	|
| 4.5.2           	|             	| Invoice                                                         	|                                                                                                                                                                                                                                                                                                                                        	| não aplicável 	|
| 4.5.2.1         	|      *      	| Identificação do documento de Compra (InvoiceNo)                	| Número original do documento de compra                                                                                                                                                                                                                                                                                                 	|    Texto 60   	|
| 4.5.2.2         	|             	| Chave do documento (Hash)                                       	| O campo deve ser preenchido com “0” (zero), caso não haja obrigatoriedade de validação.                                                                                                                                                                                                                                                	|   Texto 172   	|
| 4.5.2.3         	|      *      	| Código do utilizador (SourceID)                                 	| Utilizador que gerou o documento.                                                                                                                                                                                                                                                                                                      	|    Texto 60   	|
| 4.5.2.4         	|             	| Período contabilístico (Period)                                 	| Deve ser indicado o mês do período de tributação de “1” a “12”, contado desde o seu início.                                                                                                                                                                                                                                            	|    Inteiro    	|
| 4.5.2.5         	|      *      	| Data do documento de compra (InvoiceDate)                       	| Data de emissão do documento de compra de bens ou serviços.                                                                                                                                                                                                                                                                            	|      Data     	|
| 4.5.2.6         	|      *      	| Tipo de documento (PurchaseType)                                	| Deve ser preenchido com:  "FT” – Factura;  “FR” – Factura/recibo;  “GF” – Factura genérica;  “FG” -Factura global  “AC” – Aviso de cobrança  “RE” – Recibo  “ND” – Nota de débito “NC” – Nota de crédito  “AF” – Factura/recibo (autofacturação) “TV” – Talão de venda; “TS” – Talão de serviços prestados; “NL” – Nota de liquidação; 	|    Texto 2    	|
| 4.5.2.7         	|      *      	| Identificador do Fornecedor (SupplierID)                        	| Identificador único do fornecedor (SupplierID). Pode indicar o número de identificação fiscal do Fornecedor ou chave única da tabela 2.4. – (SupplierID) respeitando a regra aí definida para o campo.                                                                                                                                 	|    Texto 30   	|
| 4.5.2.8         	|             	| Totais do documento (DocumentTotals)                            	|                                                                                                                                                                                                                                                                                                                                        	| não aplicável 	|
| 4.5.2.8.1       	|      *      	| Valor do imposto (TaxPayable)                                   	| Imposto suportado (IVA)                                                                                                                                                                                                                                                                                                                	|   Monetário   	|
| 4.5.2.8.2       	|      *      	| Base tributável (TaxBase)                                       	| Base tributável do imposto                                                                                                                                                                                                                                                                                                             	|   Monetário   	|
| 4.5.2.8.3       	|      *      	| Total do documento com impostos (GrossTotal)                    	| Valor total do documento com imposto                                                                                                                                                                                                                                                                                                   	|   Monetário   	|
| 4.5.2.8.4       	|             	| IVA dedutível (Deductible)                                      	| Existindo a necessidade de efectuar mais do que uma referência, esta estrutura poderá ser gerada tantas vezes quantas as necessárias.                                                                                                                                                                                                  	| não aplicável 	|
| 4.5.2.8.4.1     	|      *      	| Imposto dedutível (DeductibeAmount)                             	| Este campo deve incluir o imposto dedutível por factura.                                                                                                                                                                                                                                                                               	|   Monetário   	|
| 4.5.2.8.4.2     	|      *      	| Direito de Dedução (DeductiblePercentage)                       	| Percentagem de imposto deduzido.                                                                                                                                                                                                                                                                                                       	|    Decimal    	|
| 4.5.2.8.4.3     	|      *      	| Tipologia ou linha de destino para DP de IVA (DeductibeTaxType) 	| Deve ser preenchido com:  "MFI" - Meios Fixos e Investimentos    "INV" - Existências/Inventário     "OBC" - Outros Bens de Consumo     "SERV" - Serviços     "IMPORT" - Importação      "SCE" - Serviços Contratados no Estrangeiro                                                                                                    	|    Texto 6    	|
| 4.5.2.8.4.4     	|             	| Retenções de imposto (WithholdingTax)                           	| Existindo a necessidade de efetuar mais do que uma referência, esta estrutura poderá ser gerada tantas vezes quantas as necessárias.                                                                                                                                                                                                   	| não aplicável 	|
| 4.5.2.8.4.4.1   	|      *      	| Código do tipo de imposto retido (WithholdingTaxType)           	| Neste campo deve ser indicado o tipo de imposto retido, preenchendo-o com:   “IRT” – Imposto sobre o rendimento de trabalho;    “II” – Imposto sobre o industrial;    “IS” – Imposto do selo;   "IVA" - Imposto sobre o Valor Acrescentado, quando sujeito a retenção/cativação.                                                       	|    Texto 3    	|
| 4.5.2.8.4.4.2   	|             	| Motivo da retenção na fonte (WithholdingTaxDescription)         	| Deve ser indicado o normativo legal aplicável ou a percentagem de imposto aplicável.                                                                                                                                                                                                                                                   	|    Texto 60   	|
| 4.5.2.8.4.4.3   	|      *      	| Montante de imposto retido (WithholdingTaxAmount)               	| Deve ser indicado o montante retido de imposto.                                                                                                                                                                                                                                                                                        	|   Monetário   	|
| 4.5.2.8.5       	|             	| Moeda (Currency)                                                	|                                                                                                                                                                                                                                                                                                                                        	| não aplicável 	|
| 4.5.2.8.5.1     	|      *      	| Código de moeda (CurrencyCode)                                  	| No caso de moeda estrangeira deve ser preenchido de acordo com a norma ISO 4217.                                                                                                                                                                                                                                                       	|    Texto 3    	|
| 4.5.2.8.5.2     	|      *      	| Valor total em moeda estrangeira (CurrencyAmount)               	| Total do documento com impostos (GrossTotal) na moeda original do documento.                                                                                                                                                                                                                                                           	|   Monetário   	|
| 4.5.2.8.5.3     	|      *      	| Taxa de câmbio (ExchangeRate)                                   	| Deve ser indicada a taxa de câmbio utilizada na conversão para AOA.                                                                                                                                                                                                                                                                    	|    Decimal    	|


## Documentos de suporte

- [Resources\312-18 Alterar.docx](https://github.com/assoft-portugal/SAF-T-AO/blob/dev_PurchaseInvoices/Resources/312-18%20Alterar.docx)
- [Resources\312-18-PurchaseInvoices.xlsx](https://github.com/assoft-portugal/SAF-T-AO/blob/dev_PurchaseInvoices/Resources/312-18-PurchaseInvoices.xlsx)

## Commits

- Apresentação da nova estrutura f6dbef659b730bf91cd2b45b0a63d5f921e13a07
- Atualização de alguns elementos que não impactam com esta parte da estrutura, mas que vão sofrer alterações com a nova alteração legislativa 17beca80d2102dd40fc0626204e7fc950ff3a998
- Contributos recebidos para a nova estrutura 2079885cdf62226bf0166e7901fca7fb76048975

## Branch

https://github.com/assoft-portugal/SAF-T-AO/commits/dev_PurchaseInvoices

## XSD Schema

[XSD\SAFTAO1.01_01.xsd](https://github.com/assoft-portugal/SAF-T-AO/blob/dev_PurchaseInvoices/XSD/SAFTAO1.01_01.xsd)

**Comment by cryptolopes** [comment]
> # Proposta de alteração da estrutura PurchaseInvoices

Os vossos contributos são bem vindos. Peço a todos que testem e critiquem, considerando a importância desta estrutura para o preenchimento automático do anexo de fornecedores da `DPIVA`.

**Comment by sgouveia2919** [comment]
Boa tarde, 
Procedi ás alterações conforme o quadro acima para o PurchaseInvoices e ao submeter no Portal da AGT os erros que ocorriam mantêm-se.

**Comment by cryptolopes** [comment]
> Boa tarde,
> Procedi ás alterações conforme o quadro acima para o PurchaseInvoices e ao submeter no Portal da AGT os erros que ocorriam mantêm-se.

Ainda estamos em fase de proposta. 😁

**Comment by MiguelSilva-PBSS** [comment]
Boa tarde segue a nossa proposta de alteração à nova estrutura apresentada:

4.5.2: Alterar o nome do campo para "Documento de Compra (Invoice)"

4.5.2.1: Alterar o nome do campo para "Identificação única do documento de Compra (InvoiceNo)". Nas notas técnicas deste campo sugerimos que deve ser definida a estrutura do Invoice Number.

4.5.2.8.4.3: Alterar as notas técnicas para "Existindo a necessidade de efectuar mais do que uma referência, esta estrutura poderá ser gerada tantas vezes quantas as necessárias. Deve ser preenchido com: "MFI" - Meios Fixos e Investimentos "INV" - Existências/Inventário "OBC" - Outros Bens de Consumo ". Numa fatura podemos ter, artigos do tipo mercadoria (INV) e do tipo serviços (SERV).

Notas adicionais:
Na estrutura apresentada não contempla o IVA Cativo, (na óptica do iva cativado a fornecedores), a estrutura actual do modelo 7 da DP IVA contém este cenário. Para efeitos do controlo do IVA Cativo pensamos que a estrutura devia suportar este cenário.

Para efeitos de suporte de cenários de faturas com múltipla taxa de iva e\ou múltipla tipologia, sugerimos que as linhas dos documentos de compra estejam suportadas neste documento.

Caso esta estrutura venha a suportar as linhas dos documentos, e sejam adicionadas estruturas de referência tal como acontece no SAF-T de faturação, esta estrutura do saft de compras permitiria adicionalmente, na nossa opinião, o preenchimento do anexo de regularizações de fornecedores.

Cumprimentos.

**Comment by cryptolopes** [comment]
> 4.5.2: Alterar o nome do campo para "Documento de Compra (Invoice)"

9dd8e4761de34abe20b829bf8853ae5e37135e08 ✔

> Na estrutura apresentada não contempla o IVA Cativo, (na óptica do iva cativado a fornecedores), a estrutura actual do modelo 7 da DP IVA contém este cenário. Para efeitos do controlo do IVA Cativo pensamos que a estrutura devia suportar este cenário.

1fcc12ff6bae50e3fd44208d318e091a83699c5e ✔

**Comment by sgouveia2919** [comment]
Bom dia, 

Estou com dificuldade em validar um ficheiro gerado com a versão atual do XSD.
Sabem qual o XSD que o portal da finanças de Angola está a considerar para vlaidar o ficheiro SAFT?
Se sim, podem disponibilizar?

Obrigada, 
Sandra Gouveia

**Comment by sgouveia2919** [comment]
Bom dia, 

Uma vez que o XSD que tenho não corresponde ao que o portal de finanças de Angola está a usar resolvi fazer uma alteração às TAGS do ficheiro de Aquisição de Bens e Serviços.
Onde estava:
 - Invoice coloquei PurchaseInvoice
 - InvoiceNo coloquei PurchaseInvoiceNo
- InvoiceDate coloquei PurchaseInvoiceDate
- InvoiceType coloquei PurchaseInvoiceType

Submeti um ficheiro com estas alterações e estranhamente o validador deixou de devolver os erros que até agora devolvia (campo xpto está na posição errada).
Agradeço comentário!

Obrigada, 
Sandra Gouveia

**Comment by Schobert** [comment]
@cryptolopes 

Na estrutura que descreves em cima o campo 4.5.2.9.1 | * | Código do tipo de imposto retido (WithholdingTaxType) prevê várias opções (“IRT”; “II”; “IS”; "IVA";). 
Na versão que eu tenho (e que supostamente não ia ser mais alterada) este campo só prevê o preenchimento com IVA no caso de IVA cativo, e mais nenhuma opção. Isto foi também confirmado com a AGT. 

Qual estará certa??

**Comment by Schobert** [comment]
Na estrutura que descreves em cima o campo 4.5.2.9.1 | * | Código do tipo de imposto retido (WithholdingTaxType) prevê várias opções (“IRT”; “II”; “IS”; "IVA";).  
Acabei de receber a nova versão da proposta de lei (e também a anterior) e este campo só prevê o preenchimento com IVA no caso de IVA cativo, e mais nenhuma opção. Isto foi também confirmado com a AGT.  
 
Qual estará certa??

**Comment by cryptolopes** [comment]
> Qual estará certa??

Olá @Schobert,
A solução proposta está certa.

https://github.com/assoft-portugal/SAF-T-AO/blob/600212f8bf329447b04b01d610d8de28ed63162c/XSD/SAFTAO1.01_01.xsd#L1624-L1645

**Comment by Schobert** [comment]
Olá @cryptolopes , 
então temos discrepâncias entre o XSD e o conteúdo da **_Alteração do anexo I do Decreto Presidencial n.º 312/18, de 3 de Dezembro (PROPOSTA DE DECRETO EXECUTIVO)_**?
O que está nas notas técnicas são regras explícitas do decreto, e para todos os efeitos fazem parte do decreto. 
Todas as regras devem ser explícitas (já me estou a repetir, eu sei :) ).
