### ISSUE TITLE
Ficheiro saf-t gerado pelo software não valida

### ISSUE THREAD

**Issue by Fkain62** [assoft-portugal/SAF-T-AO#21]
Por favor ajudem-me a resolver essa situação o arquivo xml não passa no validor da agt @cryptolopes

**Comment by Fkain62** [comment]
-

**Comment by cryptolopes** [comment]
@Fkain62 
Tem de colocar aqui os ficheiros.

**Comment by Fkain62** [comment]
![IMG-20191001-WA0004](https://user-images.githubusercontent.com/56027525/65989509-c6478200-e481-11e9-9257-5d145649569a.jpg)
![IMG-20191001-WA0005](https://user-images.githubusercontent.com/56027525/65989511-c6e01880-e481-11e9-8ef5-856607ee615e.jpg)
![IMG-20191001-WA0006](https://user-images.githubusercontent.com/56027525/65989516-c778af00-e481-11e9-9adc-ec331ef741c4.jpg)
![IMG-20191001-WA0007](https://user-images.githubusercontent.com/56027525/65989518-c778af00-e481-11e9-8531-3c218aab33e4.jpg)

**Comment by Fkain62** [comment]
No meu repositório tem o xml como deve ser

**Comment by Fkain62** [comment]
<?xml version="1.0" standalone="yes"?>
<NewDataSet>
  <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="tbl" msdata:UseCurrentLocale="true">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="tbl">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="ID" type="xs:int" minOccurs="0" />
                <xs:element name="Empresa" type="xs:string" minOccurs="0" />
                <xs:element name="Morada" type="xs:string" minOccurs="0" />
                <xs:element name="NIF" type="xs:string" minOccurs="0" />
                <xs:element name="Telefone" type="xs:string" minOccurs="0" />
                <xs:element name="Factura" type="xs:string" minOccurs="0" />
                <xs:element name="Data" type="xs:dateTime" minOccurs="0" />
                <xs:element name="Chave" type="xs:string" minOccurs="0" />
                <xs:element name="Validade" type="xs:string" minOccurs="0" />
                <xs:element name="Quantidade" type="xs:int" minOccurs="0" />
                <xs:element name="Produto" type="xs:string" minOccurs="0" />
                <xs:element name="Preco_Unitario" type="xs:float" minOccurs="0" />
                <xs:element name="IVA" type="xs:int" minOccurs="0" />
                <xs:element name="Total" type="xs:float" minOccurs="0" />
                <xs:element name="Funcionario" type="xs:string" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:complexType>
    </xs:element>
  </xs:schema>
  <tbl>
    <ID>1</ID>
    <Empresa>JS.MAURICIO</Empresa>
    <Morada>Bairro do Lucrecia</Morada>
    <NIF>2171072415</NIF>
    <Telefone>923359596-938838545</Telefone>
    <Factura>Fat-1</Factura>
    <Data>2019-09-30T00:00:00+01:00</Data>
    <Chave>AXM19JYPLNBIHK</Chave>
    <Validade>Processado por programa validado n.1.1/AGT19</Validade>
    <Quantidade>2</Quantidade>
    <Produto>Produto exemplo 1 sem iva</Produto>
    <Preco_Unitario>50.1</Preco_Unitario>
    <IVA>0</IVA>
    <Total>100.2</Total>
    <Funcionario>Operador1</Funcionario>
  </tbl>
</NewDataSet>

**Comment by cryptolopes** [comment]
Referia-me ao ficheiro XML.
Em todo o caso esses prints não parecem ser de um SAF-T.

**Comment by Fkain62** [comment]
Ok, em anexo tem o xml que extrai do softwareEm 01/10/2019 19:59, Nelson <notifications@github.com> escreveu:Referia-me ao ficheiro XML.

Em todo o caso esses prints não parecem ser de um SAF-T.

**Comment by Fkain62** [comment]
Agora entendo que eu  não percebo nada sobre o saf-t. Achei que fossem facturas de vendas.Por favor se der me diz como é deve ser e envia- me um xml do saf-t validado pra me basear nele.Saudações Em 01/10/2019 23:16, Fernando Cabral <fcabral62@yahoo.com.br> escreveu:Ok, em anexo tem o xml que extrai do softwareEm 01/10/2019 19:59, Nelson <notifications@github.com> escreveu:Referia-me ao ficheiro XML.

Em todo o caso esses prints não parecem ser de um SAF-T.

**Comment by Fkain62** [comment]
<?xml version="1.0" standalone="true"?>

-<NewDataSet>


-<xs:schema xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="" id="NewDataSet">


-<xs:element msdata:UseCurrentLocale="true" msdata:MainDataTable="tbl" msdata:IsDataSet="true" name="NewDataSet">


-<xs:complexType>


-<xs:choice maxOccurs="unbounded" minOccurs="0">


-<xs:element name="tbl">


-<xs:complexType>


-<xs:sequence>

<xs:element name="ID" minOccurs="0" type="xs:int"/>

<xs:element name="Empresa" minOccurs="0" type="xs:string"/>

<xs:element name="Morada" minOccurs="0" type="xs:string"/>

<xs:element name="NIF" minOccurs="0" type="xs:string"/>

<xs:element name="Telefone" minOccurs="0" type="xs:string"/>

<xs:element name="Factura" minOccurs="0" type="xs:string"/>

<xs:element name="Data" minOccurs="0" type="xs:dateTime"/>

<xs:element name="Chave" minOccurs="0" type="xs:string"/>

<xs:element name="Validade" minOccurs="0" type="xs:string"/>

<xs:element name="Quantidade" minOccurs="0" type="xs:int"/>

<xs:element name="Produto" minOccurs="0" type="xs:string"/>

<xs:element name="Preco_Unitario" minOccurs="0" type="xs:float"/>

<xs:element name="IVA" minOccurs="0" type="xs:int"/>

<xs:element name="Total" minOccurs="0" type="xs:float"/>

<xs:element name="Funcionario" minOccurs="0" type="xs:string"/>

</xs:sequence>

</xs:complexType>

</xs:element>

</xs:choice>

</xs:complexType>

</xs:element>

</xs:schema>


-<tbl>

<ID>1</ID>

<Empresa>JS.MAURICIO</Empresa>

<Morada>Bairro do Lucrecia</Morada>

<NIF>2171072415</NIF>

<Telefone>923359596-938838545</Telefone>

<Factura>Fat-1</Factura>

<Data>2019-09-30T00:00:00+01:00</Data>

<Chave>AXM19JYPLNBIHK</Chave>

<Validade>Processado por programa validado n.1.1/AGT19</Validade>

<Quantidade>2</Quantidade>

<Produto>Produto exemplo 1 sem iva</Produto>

<Preco_Unitario>50.1</Preco_Unitario>

<IVA>0</IVA>

<Total>100.2</Total>

<Funcionario>Operador1</Funcionario>

</tbl>

</NewDataSet>
