### ISSUE TITLE
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.2Invoice (FR MOM2024/02)

### ISSUE THREAD

**Issue by ithustle** [assoft-portugal/SAF-T-AO#233]
Boa tarde, caríssimos.

Estamos a desenvolver a nossa plataforma para que consequentemente passe para a fase de certificação. Submetemos o SAFT no portal da AGT para testá-lo e o erro que temos é na segunda factura. 

Olhamos para a issue #49, nos deu alguma luz relacionado ao que estavámos a fazer mas ainda assim permanece. 
Estamos a usar NodeJS e Typescript no backend e é lá aonde estamos a gerar e assinar a factura. 

Anexo aqui o erro proveniente do portal, o ficheiro SAFT gerado pela nossa aplicação e a chave pública.

Já estamos há dois dia nisso e chegamos e graças à Deus encontramos esse repositório, onde prevemos ser a nossa solução

Cmpts.

![image](https://github.com/assoft-portugal/SAF-T-AO/assets/5114680/1b03ee61-a81c-4499-97f5-7709be3ee113)
[SAFT.txt](https://github.com/assoft-portugal/SAF-T-AO/files/14312672/SAFT.txt)

```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDn8GIFYit8GMP4BW6JmqVdomNF
Dhck5a3EYoJxgRlwYX2yOZ+LqTl1mgY2QUrKez5SoS7U0DglX+AWihDY36ISWtiR
aZKJvTGZtuag1S6KY7ofbEaCq1buT/QG58KOUDshHfFme8e0uD/8BOGAkYHnkxTP
mMd7BEPaOJ5jkXNM/wIDAQAB
-----END PUBLIC KEY-----
```

**Comment by helineth** [comment]
@cryptolopes

**Comment by ithustle** [comment]
Problema resolvido. Obrigado!
