### ISSUE TITLE
Purchase Invoice: InvoiceNo deve ser string sem pattern

### ISSUE THREAD

**Issue by Schobert** [assoft-portugal/SAF-T-AO#31]
No campo InvoiceNo das Aquisições exige-se presentemente que cumpra o pattern igual ao das faturas de vendas (tipo interno de documento, espaço, série, barra, número interno. 
Isso não faz sentido porque a fatura pode ter uma numeração diferente deste padrão, basta ser uma fatura estrangeira.
Além disso não permite duplicados. Isso também não faz sentido, porque pode haver um número igual de fornecedores diferentes.

**Comment by cryptolopes** [comment]
Faz sentido https://github.com/assoft-portugal/SAF-T-AO/blob/14009f3c7a1c6c66f054cb70fd266f27664dce77/XSD/SAFTAO1.01_01.xsd#L680

**Comment by cryptolopes** [comment]
Duplicate of #20
