### ISSUE TITLE
Validador Falha no TaxPayable se existir um desconto

### ISSUE THREAD

**Issue by pcasqueiro** [assoft-portugal/SAF-T-AO#36]
Caros,
após alguns testes, o erro do TaxPayable parece estar relacionado com o facto de existir um desconto e não relacionado com arrendondamentos. 
Deixo em anexo dois exemplos: um que falha a dizer que o TaxPayable está errado e outro, sem Settlement, que passa no validador. 
Conseguem ajudar ? 
[SAFT-APENAS 1 DOC - Falha TaxPayable.xml.txt](https://github.com/assoft-portugal/SAF-T-AO/files/3787585/SAFT-APENAS.1.DOC.-.Falha.TaxPayable.xml.txt)
[SAFT-APENAS 1 DOC - Sem Settlement.xml.txt](https://github.com/assoft-portugal/SAF-T-AO/files/3787587/SAFT-APENAS.1.DOC.-.Sem.Settlement.xml.txt)

obrigado,
Pedro

**Comment by cryptolopes** [comment]
Atenção, a plataforma da AGT valida outras regras que não são possíveis validar pelo schema. Por exemplo, valida razões de cálculo.

Em [SAFT-APENAS 1 DOC - Falha TaxPayable.xml.txt](https://github.com/assoft-portugal/SAF-T-AO/files/3787585/SAFT-APENAS.1.DOC.-.Falha.TaxPayable.xml.txt) existe de facto um **erro de preenchimento/cálculo**.

O represente do elemento `SettlementAmount` afeta os valores "normais" de `UnitPrice`, `CreditAmount `ou `DebitAmount`. Estes elementos têm de deduzir o valor do desconto. 

InvoiceNo | InvoiceType | Quantity | UnitPrice | CreditAmount | SettlementAmount | TaxPayable | NetTotal | GrossTotal
-- | -- | -- | -- | -- | -- | -- | -- | --
FR Z1.2019/7 | FR | 100.00 | 0.55000 | 45.00000 | 10.00000 | 6.30 | 45.00 | 51.30
  |   |   |   |   |   |   |   |  
Correto |   |   | **0.45000** | 45.00000 | 10.00000 | 6.30 | 45.00 | 51.30

**Comment by cryptolopes** [comment]
#32 
Atenção a isto!
Os elementos devem estar preenchidos em conformidade com o estabelecido na [Lei](https://github.com/assoft-portugal/SAF-T-AO/blob/master/Resources/DP%20312.18%20SAF-T.pdf).
