### ISSUE TITLE
Campo SoftwareValidationNumber não deve ser numerico no XSD

### ISSUE THREAD

**Issue by pcasqueiro** [assoft-portugal/SAF-T-AO#37]
Iniciámos a submissão de ficheiro de SAFT-AO e deu um erro. Após confirmação com a AGT, pediram para alterarmos o campo SoftwareValidationNumber de "204" para 204/AGT/2019. Com esta alteração já foi possivel submeter o ficheiro SAFT-AO, MAS a validação contra o XSD dá erro:
Severity: error
Description: '204/AGT/2019' is not a valid value for 'integer'.
Start location: 26:35
End location: 26:47
Severity: error
Description: The value '204/AGT/2019' of element 'SoftwareValidationNumber' is not valid.
Start location: 26:35
End location: 26:47

O validador online da AGT não dá qualquer erro.

Podem, por favor, fazer reflectir esta opção de string nnn/AGT/yyyy no XSD ?

obrigado,
Pedro Casqueiro
TEXTO EDITORES

**Comment by cryptolopes** [comment]
fixed 14009f3c7a1c6c66f054cb70fd266f27664dce77
