### ISSUE TITLE
Pedido de esclarecimento

### ISSUE THREAD

**Issue by Victor-Correia** [assoft-portugal/SAF-T-AO#38]
1.	Quanto a tabela de imposto, DP 312/18, campo 2.5.1.4, quando se tratar de IVA não aplicável ou não sujeito, como deverá ser preenchida informação no ficheiro XML? Preenchemos com 0 ou N/A (não aplicável)?
2.	Ainda sobre as tabelas do mesmo decreto, para o ficheiro F, referente a facturação, o mesmo não contempla dados de forncedores na sua descrição. A nossa dúvida consiste no seguinte: caso o software de facturação comtemple dados dos forncedores, deveremos incluí-los no ficheiro XML ou não?

**Comment by Victor-Correia** [comment]
Boa tarde,
Gostaríamos, igualmente, que nos enviassem um exemplo desecriptado do modelo R (Recibos - Ficheiros XML)

**Comment by cryptolopes** [comment]
> Boa tarde,
> Gostaríamos, igualmente, que nos enviassem um exemplo desencriptado do modelo R (Recibos - Ficheiros XML)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<SourceDocuments xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:OECD:StandardAuditFile-Tax:AO_1.01_01 https://raw.githubusercontent.com/assoft-portugal/SAF-T-AO/master/XSD/SAFTAO1.01_01.xsd">
    <Payments>
        <!-- Exemplo de um recibo emitido para uma fatura, simples. -->
        <NumberOfEntries>1</NumberOfEntries>
        <TotalDebit>0</TotalDebit>
        <TotalCredit>100.00</TotalCredit>
        <Payment>
            <PaymentRefNo>REC S01/1</PaymentRefNo>
            <Period>1</Period>
            <TransactionDate>2019-01-01</TransactionDate>
            <PaymentType>RC</PaymentType>
            <Description>string</Description>
            <SystemID>string</SystemID>
            <DocumentStatus>
                <PaymentStatus>N</PaymentStatus>
                <PaymentStatusDate>2019-01-01T00:00:00</PaymentStatusDate>
                <Reason>string</Reason>
                <SourceID>string</SourceID>
                <SourcePayment>P</SourcePayment>
            </DocumentStatus>
            <PaymentMethod>
                <PaymentMechanism>CC</PaymentMechanism>
                <PaymentAmount>100.00</PaymentAmount>
                <PaymentDate>2019-01-01</PaymentDate>
            </PaymentMethod>
            <SourceID>string</SourceID>
            <SystemEntryDate>2019-01-01T00:00:00</SystemEntryDate>
            <CustomerID>string</CustomerID>
            <Line>
                <LineNumber>1</LineNumber>
                <SourceDocumentID>
                    <OriginatingON>string</OriginatingON>
                    <InvoiceDate>1973-04-04</InvoiceDate>
                    <Description>string</Description>
                </SourceDocumentID>
                <CreditAmount>100.00</CreditAmount>
            </Line>
            <DocumentTotals>
                <TaxPayable>0.00</TaxPayable>
                <NetTotal>100.00</NetTotal>
                <GrossTotal>100.00</GrossTotal>
            </DocumentTotals>
        </Payment>
    </Payments>
</SourceDocuments>
```

**Comment by cryptolopes** [comment]
> Quanto a tabela de imposto, DP 312/18, campo 2.5.1.4, quando se tratar de IVA não aplicável ou não sujeito, como deverá ser preenchida informação no ficheiro XML? Preenchemos com 0 ou N/A (não aplicável)?

Ver **[TaxExemptions.json](https://github.com/assoft-portugal/SAF-T-AO/blob/master/Resources/TaxExemptions.json)** ou **[Wiki Tax Exemption Codes](https://github.com/assoft-portugal/SAF-T-AO/wiki/Tax-Exemption-Codes)**

### TaxTable

```xml
<?xml version="1.0" encoding="utf-8" ?>
<TaxTable xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:OECD:StandardAuditFile-Tax:AO_1.01_01 https://raw.githubusercontent.com/assoft-portugal/SAF-T-AO/master/XSD/SAFTAO1.01_01.xsd">
    <TaxTableEntry>
        <TaxType>IVA</TaxType>
        <TaxCountryRegion>AO</TaxCountryRegion>
        <TaxCode>NOR</TaxCode>
        <Description>IVA Taxa Normal</Description>
        <TaxPercentage>14.00</TaxPercentage>
    </TaxTableEntry>
    <TaxTableEntry>
        <TaxType>IVA</TaxType>
        <TaxCountryRegion>AO</TaxCountryRegion>
        <TaxCode>ISE</TaxCode>
        <Description>IVA Isento</Description>
        <TaxPercentage>0.00</TaxPercentage>
    </TaxTableEntry>
</TaxTable>
```

### SalesInvoice

```xml
<?xml version="1.0" encoding="utf-8" ?>
<SourceDocuments xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:OECD:StandardAuditFile-Tax:AO_1.01_01 https://raw.githubusercontent.com/assoft-portugal/SAF-T-AO/master/XSD/SAFTAO1.01_01.xsd">
    <SalesInvoices>
        <!-- Exemplo de fatura simples -->
        <NumberOfEntries>1</NumberOfEntries>
        <TotalDebit>0</TotalDebit>
        <TotalCredit>100.00</TotalCredit>
        <Invoice>
            <InvoiceNo>FT S01/1</InvoiceNo>
            <DocumentStatus>
                <InvoiceStatus>N</InvoiceStatus>
                <InvoiceStatusDate>2019-01-01T00:00:00</InvoiceStatusDate>
                <Reason>string</Reason>
                <SourceID>string</SourceID>
                <SourceBilling>P</SourceBilling>
            </DocumentStatus>
            <Hash>string</Hash>
            <HashControl>string</HashControl>
            <Period>1</Period>
            <InvoiceDate>2019-01-01</InvoiceDate>
            <InvoiceType>FT</InvoiceType>
            <SpecialRegimes>
                <SelfBillingIndicator>0</SelfBillingIndicator>
                <CashVATSchemeIndicator>0</CashVATSchemeIndicator>
                <ThirdPartiesBillingIndicator>0</ThirdPartiesBillingIndicator>
            </SpecialRegimes>
            <SourceID>string</SourceID>
            <EACCode>00000</EACCode>
            <SystemEntryDate>2019-01-01T00:00:00</SystemEntryDate>
            <CustomerID>string</CustomerID>
            <Line>
                <LineNumber>1</LineNumber>
                <ProductCode>string</ProductCode>
                <ProductDescription>string</ProductDescription>
                <Quantity>2</Quantity>
                <UnitOfMeasure>string</UnitOfMeasure>
                <UnitPrice>50.00</UnitPrice>
                <TaxPointDate>2019-01-01</TaxPointDate>
                <Description>string</Description>
                <CreditAmount>50.00</CreditAmount>
                <Tax>
                    <TaxType>IVA</TaxType>
                    <TaxCountryRegion>AO</TaxCountryRegion>
                    <TaxCode>ISE</TaxCode>
                    <TaxPercentage>0</TaxPercentage>
                </Tax>
                <TaxExemptionReason>IVA – Regime de não sujeição</TaxExemptionReason>
                <TaxExemptionCode>M04</TaxExemptionCode>
            </Line>
            <DocumentTotals>
                <TaxPayable>0.00</TaxPayable>
                <NetTotal>100.00</NetTotal>
                <GrossTotal>100.00</GrossTotal>
            </DocumentTotals>
        </Invoice>
    </SalesInvoices>
</SourceDocuments>
```

> Ainda sobre as tabelas do mesmo decreto, para o ficheiro F, referente a facturação, o mesmo não contempla dados de forncedores na sua descrição. A nossa dúvida consiste no seguinte: caso o software de facturação comtemple dados dos forncedores, deveremos incluí-los no ficheiro XML ou não?

Entende-se por dados dos fornecedores, dados contacto `Customer`, contabilidade e documentos comerciais.  Se o objetivo for apenas o de entregar elementos relativos à faturação não creio haver necessidade de exportar os elementos relativos aos fornecedores.

**Comment by Victor-Correia** [comment]
Bom dia Caríssmos Senhores. 
Recebemos na Sexta-feira (22), vários instrutivos enviados pela AG, dentre os quais o instrutivo de número  000009/DSIVA/AGT/2019 que suscitou-nos algumas dúvidas, designamente:
1. O instrutivo refere-se ao facto de as empresas terem a obrigação de apresentar um software validado para poderem emitir facturas. A Bolloré está no regime transitório, senque que os seus softwares se encontram em processo de validação. A nossa questão: podemos continuar a emitir facturas enquanto o decorre o processo de validação?
2. Para além da certificação que AGT atribui aos softwares, há outra certificação intermédia que as empresas produtoras de software deverão receber/solicitar enquanto decorre o processo de validação que envolve a apresentação de vários elementos?

Obrigado.

**Comment by cryptolopes** [comment]
> 1. O instrutivo refere-se ao facto de as empresas terem a obrigação de apresentar um software validado para poderem emitir facturas. A Bolloré está no regime transitório, senque que os seus softwares se encontram em processo de validação. A nossa questão: podemos continuar a emitir facturas enquanto o decorre o processo de validação?

O processamento de documentos fiscalmente relevantes (faturas, notas de crédito, notas de débito, etc) carece da utilização obrigatória de software validado (certificado), não obstante do certificado ser provisório.

> 2. Para além da certificação que AGT atribui aos softwares, há outra certificação intermédia que as empresas produtoras de software deverão receber/solicitar enquanto decorre o processo de validação que envolve a apresentação de vários elementos?

Não existe outra certificação para o mesmo efeito.

**Comment by Victor-Correia** [comment]
Face a resposta apresentada no ponto 1, o que poderemos fazer para obtermos rapidamente uma certificação provisória enquanto tratamos da conformação dos nossos softwares (apresentação do XML e outros)? Pois, se simplesmente não podemos facturar enquanto tratamos da parte do software, isso implica a paralisação da empresa com todas as consequências que daí podem advir.

**Comment by cryptolopes** [comment]
> o que poderemos fazer para obtermos rapidamente uma certificação provisória enquanto tratamos da conformação dos nossos softwares (apresentação do XML e outros)? 

Devem iniciar o processo junto da AGT e concluir com sucesso os respetivos requisitos.

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments). 
1 - Na minha factura (FT) têm duas linhas.
          <LineNumber>1</LineNumber>
         <CreditAmount>100000.00</CreditAmount>
         <TaxPercentage>14</TaxPercentage>
       
       <LineNumber>2</LineNumber>
         <CreditAmount>50000.00</CreditAmount>
         <TaxPercentage>0</TaxPercentage>
Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments). 
1 - Na minha factura (FT) têm duas linhas.
          <LineNumber>1</LineNumber>
         <CreditAmount>100000.00</CreditAmount>
         <TaxPercentage>14</TaxPercentage>
       
       <LineNumber>2</LineNumber>
         <CreditAmount>50000.00</CreditAmount>
         <TaxPercentage>0</TaxPercentage>
Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments). 
1 - Na minha factura (FT) têm duas linhas.

          <LineNumber>1</LineNumber>
         <CreditAmount>100000.00</CreditAmount>
         <TaxPercentage>14</TaxPercentage>
       
       <LineNumber>2</LineNumber>
         <CreditAmount>50000.00</CreditAmount>
         <TaxPercentage>0</TaxPercentage>
Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by MANUEL2810** [comment]
Adriano esta tambem é a minha questão
