### ISSUE TITLE
Pedido de esclarecimento ficheiro XML

### ISSUE THREAD

**Issue by VictorHugoCorreia** [assoft-portugal/SAF-T-AO#40]
Boa tarde Caros Senhores,

Solicitamos o esclarecimento das seguintes dúvidas abaixo, relativamente ao ficheiro XML:

1- No campo 2.4.1_ Indicador de produto ou service, devemos prrencher com P, S, O, E ou T, no nosso entendimento o O - Outros, deve ser usado para o caso dos adiantamentos, e outros, o que significa que sempre que não se aplicar o P, S ou T, confirmam? O que consideram impostos, taxas e encargos parafiscais, podem sff dar exemplos. Utilizamos E- Imposto especiais de consumo, quando? podem darnos alguns exemplos.

2- Para o campo 2.5.1.4- Descrição do imposto, no decreto, têm a seguinte redação: "No caso de imposto de selo deve ser preenchido com a descrição da verba respectiva," ou seja no nosso entendimento com o valor do imposto de selo e quando se tratem de outros impostos como o IVA, ou nenhum imposto, como preencher, com o valor do IVA e em branco respectivamente ou zero? vimos um exemplo em que este campo foi preenchido com IVA Isento e com IVA a taxa Normal, com que outras descrições pode ser prrenchido? no caso de não sujeição por exemplo.

3- O campo 4.1.4.3.1 - Estado actual do document, deve ser preenchido com:
N- normal;
S- Autofacturação;
R - documento de resumo doutros documentos criados noutras aplicações e gerado nesta aplicação;
F- documento facturado;

Quando devemos usar cada um deles? o que se considera um estado do documento N - normal? Podem dar-nos um exemplo do tipo R, não percebemos o que é um documento de resumo doutros documentos criados noutras aplicações e gerado nesta aplicação, podem sff exclarecer.

4- 4.1.4.19.12.1 - Numero de série, para o caso de serviços, não se aplicam os numeros de série, como preencher este campo? com NA - Não aplicavel; deixar em branco; com zero, por extenso ou zero numero?, sendo que o campo é de Texto.

5- 4.1.4.20.6.2 - Montante do pagamento, deve ser indicado o montante por cada tipo de pagamento, o nosso entendimento é que aqui para cada factura deve ser indicado o valor recebido, de acordo com o tipo de pagamento usado pelo cliente, ou seja se a factura foi paga por transferência bancária e dinheiro, devemos preencher com o montante pago em dinheiro e em transferência bancária?

6-para os campos não obrigatorios ou não aplicaveis, devemos simplesmente não preencher, ou colocar N/A - Não aplicave, ou colocar zero?

Ficamos aguardar.
Muito obrigada.

**Comment by cryptolopes** [comment]
> 1- No campo 2.4.1_ Indicador de produto ou service, devemos prrencher com P, S, O, E ou T, no nosso entendimento o O - Outros, deve ser usado para o caso dos adiantamentos, e outros, o que significa que sempre que não se aplicar o P, S ou T, confirmam? O que consideram impostos, taxas e encargos parafiscais, podem sff dar exemplos. Utilizamos E- Imposto especiais de consumo, quando? podem darnos alguns exemplos.

https://github.com/assoft-portugal/SAF-T-AO/blob/572a3c26cd10400c4b950ac9bd177cd121b4468c/XSD/SAFTAO1.01_01.xsd#L1351-L1372

> como preencher, com o valor do IVA e em branco respectivamente ou zero? 

Duplicate of https://github.com/assoft-portugal/SAF-T-AO/issues/38#issuecomment-557156932

> 3- O campo 4.1.4.3.1 - Estado actual do document, deve ser preenchido com:
> N- normal;
> S- Autofacturação;
> R - documento de resumo doutros documentos criados noutras aplicações e gerado nesta aplicação;
> F- documento facturado;
> 
> Quando devemos usar cada um deles? 

- N - todos os documentos contabilizados emitidos pela aplicação informática)
- S - documentos "normais" lançados em regime de auto-faturação
- R - documento integrado ou recuperado através de uma cópia impressa, por exemplo
- F - documento original que posteriormente foi F (implica a existência de um documento classificado como N e a respetiva relação entre ambos. por exemplo, uma **Venda-a-Dinheiro** que posteriormente deu origem a **Fatura**. Encontra-se previsto no SAF-T, mas tal e qual como está a Legislação tem pouco ou nenhum efeito prático.)
 
> 4- 4.1.4.19.12.1 - Numero de série, para o caso de serviços, não se aplicam os numeros de série, como preencher este campo?

https://github.com/assoft-portugal/SAF-T-AO/blob/df08c9321383a1b98f2120341a16db95acc5641a/XSD/SAFTAO1.01_01.xsd#L408

O elemento não é obrigatório. Se não existem dados para preencher o elemento, ele simplesmente não é inserido.

> 5- 4.1.4.20.6.2 - Montante do pagamento, deve ser indicado o montante por cada tipo de pagamento

https://github.com/assoft-portugal/SAF-T-AO/blob/df08c9321383a1b98f2120341a16db95acc5641a/XSD/SAFTAO1.01_01.xsd#L429

Sim, tem de ser. Um elemento por cada tipo.

> 6-para os campos não obrigatorios ou não aplicaveis, devemos simplesmente não preencher, ou colocar N/A - Não aplicave, ou colocar zero?

Não inserir no SAF-T

**Comment by cryptolopes** [comment]
#38

**Comment by VictorHugoCorreia** [comment]
Bom dia Caríssimos,

A nossa equipa de desenvolvedores do file XML está baseada em França. Estamos numa fase crucial do processo em que a rapidez e clarificação das questões levantadas é fundamental. Gostaríamos de saber se AGT/Equipa Assoft estaria disponível para: 1. Responder a questões colocadas directamente em Inglês/Francês (nesse forúm ou por e-mail). 2. Poder participar em conf call solicitadas por nós (em Inglês).

2. Poderia indicar-nos uma plataforma/meio de podermos testar o nosso ficheiro XML listando os possíveis erros?

Obrigado.

Obrigado.

**Comment by cryptolopes** [comment]
> 1. Responder a questões colocadas directamente em Inglês/Francês (nesse forúm ou por e-mail). 

Claro que sim. Este repositório é aberto. Todos podem interagir e colaborar.

> 2. Poder participar em conf call solicitadas por nós (em Inglês).

Para esse tipo de esclarecimentos mais detalhados recomendo a utilização do Yammer. Entre em contacto **[comigo pelo Yammer](https://www.yammer.com/assoft-members/#/users/1510685188)** ou por email.

> 1. Poderia indicar-nos uma plataforma/meio de podermos testar o nosso ficheiro XML listando os possíveis erros?

Existem múltiplas ferramentas.

No meu caso, uso o [Visual Studio Code](https://code.visualstudio.com/)

Extensões:

Name: XML
Id: redhat.vscode-xml
Description: XML Language Support by Red Hat
Version: 0.9.1
Publisher: Red Hat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml

Name: XML Tools
Id: dotjoshjohnson.xml
Description: XML Formatting, XQuery, and XPath Tools for Visual Studio Code
Version: 2.5.0
Publisher: Josh Johnson
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml
