### ISSUE TITLE
Numeração de Documentos para 2020

### ISSUE THREAD

**Issue by inesandresm** [assoft-portugal/SAF-T-AO#41]
Olá bom dia a todos.

Temos aqui uma questão para a qual agradeciamos a vossa ajuda. 

Segundo as indicações que foram referidas nas conf. call da AGT a que assistimos, entendemos que todas as séries de numeração devem agora começar no número 1 (e a AGT foi bem explicita a indicar que 001 era diferente de 1).
Neste sentido, como devemos proceder se para um determinado tipo de documento (por exemplo Facturas), tivermos várias séries definidas e activas no mesmo período (por exemplo uma referente a uma loja em Luanda, outra numa loja em Cacuaco)? Não podemos repetir a numeraçao (ou seja, não podemos ter 2 facturas com o número 1) - Não é legal, nem permitido pelos proprios sistemas (Ver Imagem A, em anexo, quando tentamos "dar a volta" e usar um prefixo diferente, por exemplo):

![A_-_Erro_ao_tentar_criar_2_séries_com_range_de_numeração_sobreposta](https://user-images.githubusercontent.com/58478941/70133896-ead8f980-167e-11ea-88ad-d9eb72bc0179.png)

Neste sentido, podemos na propria range de numeração que baliza as séries incluir este prefixo, garantindo que começará por xxxx1 por exemplo  (Ver imagem B, em anexo)? 

![B_-_Solução_Alternativa_proposta_a_analisar_com_a_AGT](https://user-images.githubusercontent.com/58478941/70133924-faf0d900-167e-11ea-8727-26b191c25011.png)

Basicamente garantimos desta forma que não há repetição da numeração e que a mesma é sequencial para todos os documentos emitidos, mantendo as funcionalidades de assegurarmos várias séries por tipo de documento (o que facilita a análise e controlo dentro do negócio).

Obrigada desde já pela vossa atenção e disponibilidade para ajudar.
Inês

[SAFT_AO_Tipo_F.zip](https://github.com/assoft-portugal/SAF-T-AO/files/3921552/SAFT_AO_Tipo_F.zip)

**Comment by cryptolopes** [comment]
> [SAFT_AO_Tipo_F.zip](https://github.com/assoft-portugal/SAF-T-AO/files/3921552/SAFT_AO_Tipo_F.zip)

Um muito obrigado pela partilha do ficheiro SAF-T.
Permitiu perceber que existe uma falha no XSD, pelo facto de não prever a existência do elemento `TransactionID` em `WorkingDocuments`.

**Comment by cryptolopes** [comment]
> Segundo as indicações que foram referidas nas conf. call da AGT a que assistimos, entendemos que todas as séries de numeração devem agora começar no número 1 (e a AGT foi bem explicita a indicar que 001 era diferente de 1).

Sim, as séries devem inequivocamente iniciar-se a `1`.

> Neste sentido, como devemos proceder se para um determinado tipo de documento (por exemplo Facturas), tivermos várias séries definidas e activas no mesmo período (por exemplo uma referente a uma loja em Luanda, outra numa loja em Cacuaco)? Não podemos repetir a numeraçao (ou seja, não podemos ter 2 facturas com o número 1) - Não é legal, nem permitido pelos proprios sistemas (Ver Imagem A, em anexo, quando tentamos "dar a volta" e usar um prefixo diferente, por exemplo):
> 
> ![A_-_Erro_ao_tentar_criar_2_séries_com_range_de_numeração_sobreposta](https://user-images.githubusercontent.com/58478941/70133896-ead8f980-167e-11ea-88ad-d9eb72bc0179.png)

> Neste sentido, podemos na propria range de numeração que baliza as séries incluir este prefixo, garantindo que começará por xxxx1 por exemplo (Ver imagem B, em anexo)?

Existem de facto inúmeras soluções de software que optam por enquadrar a numeração dos documento num esquema de _range_. Isso não constitui um problema, mas recomenda-se que a range seja iniciada a `1`.

> Basicamente garantimos desta forma que não há repetição da numeração e que a mesma é sequencial para todos os documentos emitidos, mantendo as funcionalidades de assegurarmos várias séries por tipo de documento (o que facilita a análise e controlo dentro do negócio).

O formato do `InvoiceNo` deve seguir esta recomendação:

https://github.com/assoft-portugal/SAF-T-AO/blob/57fbe0f5e09f0f07804d62788f55eeda7de8c691/XSD/SAFTAO1.01_01.xsd#L1126-L1150

A existência de prefixos e outros elementos derivados da gestão ou do modelo de negócio devem passar para o lado da **série do documento**.

**Por exemplo**:

```xml
<InvoiceNo>13 752019/42</InvoiceNo>
```

**Ou totalmente em linha com a [recomendação](https://github.com/assoft-portugal/SAF-T-AO/blob/57fbe0f5e09f0f07804d62788f55eeda7de8c691/XSD/SAFTAO1.01_01.xsd#L1126-L1150
)**:

```xml
<InvoiceNo>FT 13752019/42</InvoiceNo>
```

**Comment by cryptolopes** [comment]
> [SAFT_AO_Tipo_F.zip](https://github.com/assoft-portugal/SAF-T-AO/files/3921552/SAFT_AO_Tipo_F.zip)

## Erros de estrutura identificados

`cvc-minLength-valid: Value '508183138' with length = '9' is not facet-valid with respect to minLength '10' for type 'SAFAOAngolaVatNumber'.xml(cvc-minLength-valid)`

O formato do NIF em Angola tem um mínimo de 10 caracteres.

`cvc-type.3.1.3: The value '96' of element 'SoftwareValidationNumber' is not valid.xml(cvc-type.3.1.3)`

O formato deste valor é `0/AGT/####`.

`cvc-type.3.1.3: The value 'AOA' of element 'CurrencyCode' is not valid.xml(cvc-type.3.1.3)`

A moeda de base do SAF-T AO é AOA. O elemento Currency presente nos documentos só usa em documentos emitidos em moeda estrangeira.
