### ISSUE TITLE
Validação do XML - Resposta ao modelo8

### ISSUE THREAD

**Issue by VictorHugoCorreia** [assoft-portugal/SAF-T-AO#43]
Bom dia Caríssimos,

Obtenho sempre este erro nas linhas que contenplam o IVA.

Falha na validação, AuditFile.SourceDocuments.SalesInvoices.TotalCredit da parte do ficheiro está mal calculado
--
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.3Invoice.1Line.5UnitPrice
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.3Invoice.1Line.5UnitPrice.5CreditAmount
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.4Invoice.1Line.7UnitPrice
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.4Invoice.1Line.7UnitPrice.7CreditAmount
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.7Invoice.2Line.15UnitPrice
Falha na validação de AuditFile.SourceDocuments.SalesInvoices.7Invoice.2Line.15UnitPrice.15CreditAmount

Como devemos calcular correctamente o IVA? Seguimos, inclusive, os modelos enviados pela AGT e o erro manté-mse.

**Comment by cryptolopes** [comment]
> Como devemos calcular correctamente o IVA? Seguimos, inclusive, os modelos enviados pela AGT e o erro manté-mse.

pág. [5561](https://github.com/assoft-portugal/SAF-T-AO/blob/master/Resources/DP%20312.18%20SAF-T.pdf)
