### ISSUE TITLE
Erro ao validar Contablidade integrada com a facturação

### ISSUE THREAD

**Issue by MateusCazola1** [assoft-portugal/SAF-T-AO#44]
suponhamos que eu tenha um documento sem facturas para fornecedores, o que pode acontecer com clientes que prestem apenas serviços, então sempre que for gerar saft para contablidade integrada(I), o nó Supplier é de caráter obrigatório, se passar void, ele reclama dos campos obrigatórios existentes em supplier, se retirar-mos o Nó ele diz que o nó supplier é obrigatório.
Eu acho que o xsd deveria permitir passar tais documentos que tenham apenas faturas de Clientes. pois poderemos ter sempre clientes, mais existem casos em que não teremos fornecedores.
  
 
![bug_issues](https://user-images.githubusercontent.com/59369608/71591370-57cf9a00-2b2c-11ea-9d8d-04ce3770861a.png)

**Comment by cryptolopes** [comment]
Olá @MateusCazola1
A plataforma de validação da AGT não usa apenas o schema. Também usa regras de negócio introduzidas pela própria AGT. Possivelmente, eles consideraram que quando o SAF-T contempla documentos da contabilidade é obrigatório a existência de fornecedores.

O schema não força o preenchimento desses elementos:

https://github.com/assoft-portugal/SAF-T-AO/blob/1fcc12ff6bae50e3fd44208d318e091a83699c5e/XSD/SAFTAO1.01_01.xsd#L45

**Comment by MateusCazola1** [comment]
olá @cryptolopes 
Obrigado pela informação. Gostaria eu de saber então onde poderei reportar tal situação como Bug?

**Comment by cryptolopes** [comment]
> Obrigado pela informação. Gostaria eu de saber então onde poderei reportar tal situação como Bug?

Diretamente à AGT.
