### ISSUE TITLE
ERRO VALIDAÇÃO SAF-T Falha na validação do Hash da parte AuditFile.SourceDocuments.SalesInvoices.2Invoice

### ISSUE THREAD

**Issue by 28562856** [assoft-portugal/SAF-T-AO#46]
Boa tarde pessoal,

Estou tentado validar um XML de Facturas e NC mas está me retornado o erro: Falha na validação do Hash da parte AuditFile.SourceDocuments.SalesInvoices.2Invoice, alguém saberia me dizer o que pode estar errado no HASH? Abaixo segue o XML da validação:

Exemplo:
 <InvoiceNo>FT 111111/111</InvoiceNo>
        <DocumentStatus>
          <InvoiceStatus>N</InvoiceStatus>
           <InvoiceStatusDate>2020-01-30T00:00:00</InvoiceStatusDate>
          <Reason/>
          <SourceID>3</SourceID>
          <SourceBilling>P</SourceBilling>
        </DocumentStatus>
        <Hash>q1ZOID6iCvuekctgVQdwohllU2J/krFQ0sFth/+IS7+ntBvL2V3c6FqiJZpa4dND1P49xm+C099JJVY/AH5fcBlBRhH6Gmb6df/1G3zssq3i/59pi1aVfFaoxJTYnS0slB8N7oD0uvr+vDEQo5qWdQrpSAQOX8TJVVBFHhN1J44=</Hash>
        <HashControl>1</HashControl>
        <Hash>ctwE0gmR8rabb+A+42NYq5ZtG+nVmkHCu4HeqYaeZ9MVAP1bvYlqK51MUn7ClISTww9kwL2XsVxUkqofSJmx2ll3PROKxz9rJ+ccppdzX4zjjooAq92X+b26WghEYyTZSiFpZhmSOztTI2AkoTOla1IB/yggPC5l1MSDDSf1aHU=</Hash>
        <HashControl>1</HashControl>

**Comment by cryptolopes** [comment]
> alguém saberia me dizer o que pode estar errado no HASH?

Por favor, tente fornecer informação percetível em relação ao problema.

**Comment by celsofrvieira** [comment]
Boa tarde, partilho que ontem consegui validar com sucesso um ficheiro saft e mais tarde ao repetir a validação desse mesmo ficheiro recebi a mensagem de erro conforme indicado no titulo desta thread.

Após alguma reflexão concluo que o controlo do hash presente em cada documento não deverá estar a considerar o tipo de documento. O encadeamento de documentos deve ser feito sim por serie e tipo de documento. Dessa forma, a tool de validação parece estar a verificar o encadeamento doc anterior <-> doc seguinte ignorando o tipo de documento, o que faz que so consigo sucesso na validação se só tiver 1 tipo de documento no ficheiro saft.
Acredito que é necessário ouvirmos a AGT sobre este comportamento.

A se confirmar este diagnóstico, é mandatório que ocorra algum tipo de correcção na tool de validação em uso na AGT.

**Comment by cryptolopes** [comment]
> Dessa forma, a tool de validação parece estar a verificar o encadeamento doc anterior <-> doc seguinte ignorando o tipo de documento, o que faz que so consigo sucesso na validação se só tiver 1 tipo de documento no ficheiro saft.

Obrigado pelo feedback.

**Comment by cryptolopes** [comment]
Duplicate of #49

**Comment by scarianga** [comment]
Saudações cryptolopes,
Estou a ter exactamente o mesmo problema, tenho sucesso num ficheiro com apenas uma factura mas com mais facturas tenho esse mesmo erro. Poderias ajudar-me a identificar o problema com o hash do meu ficheiro.
[PublicKey.txt](https://github.com/assoft-portugal/SAF-T-AO/files/4782859/PublicKey.txt)
[SAFT_Hash_dados.xlsx](https://github.com/assoft-portugal/SAF-T-AO/files/4782893/SAFT_Hash_dados.xlsx)

**Comment by cryptolopes** [comment]
> Poderias ajudar-me a identificar o problema com o hash do meu ficheiro.

@scarianga 

| Message                                                                                                                                                                                                                              | Verification |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|
| 2020-06-01;2020-06-01T00:00:00;FT CPE20/774241;51078.84;                                                                                                                                                                             | Verification Failure |
| 2020-06-01;2020-06-01T00:00:00;FT CPE20/774242;36686.57;HSgGA5Hutj1sXssMfpb/iPB4EREx3EHALYfDIUo/NycoYW0iCpO9RIuFclljXiYmauw2P2Csspg4whwfAGOMJCj8lJzoPBdANeZ36YCxXD+c61omAxSSFAzeUIxM+EPca4lfZ4sj+0hK+RisjOJ290qT2eSyv7x7+JwHjRJbGRo= | Verification Failure |

Não há dados da **data/hora**.

**Comment by scarianga** [comment]
Saudações @cryptolopes,
desculpa não percebi o "Não há dados da data/hora"

**Comment by cryptolopes** [comment]
@scarianga SystemEntryDate
2020-06-01T00:00:00

O timestamp não está completo.

**Comment by scarianga** [comment]
@cryptolopes, fiz algumas alterações mas mesmo assim continuo a ter erro, 
[SAFT_Hash_dados.xlsx](https://github.com/assoft-portugal/SAF-T-AO/files/4791431/SAFT_Hash_dados.xlsx) o SystemEntryDate esta no formato timestamp yyyy-mm-dd hh:mm:ss, vi alguns exmplos nos diferentes posts aqui e não vejo o que estará a faltar.

**Comment by cryptolopes** [comment]
@scarianga ver https://github.com/assoft-portugal/SAF-T-AO/issues/67#issuecomment-637856697

**Comment by juliosondev** [comment]
Saudações  Dev's!
Alguém conseguiu validar o seu HAS no portal?
