### ISSUE TITLE
Sequencial chronological numbering issue

### ISSUE THREAD

**Issue by Jamie-C84** [assoft-portugal/SAF-T-AO#47]
Dear all,
Have some of you faced this issue : it appears that the sequencial chronological numbering of the invoicing software is not considering debit notes and invoices as 2 different types of documents.
But it seems to be compulsory to have a separate numbering for each of those documents : invoices, credit notes and debit notes. To upgrade the software it will take a lot of times. 
Thank you for your help,

**Comment by cryptolopes** [comment]
> But it seems to be compulsory to have a separate numbering for each of those documents

By law, you must have separate numbering for each type of document.
