### ISSUE TITLE
Formato de InvoiceNO validado no XSD mas com erro no validador online

### ISSUE THREAD

**Issue by pcasqueiro** [assoft-portugal/SAF-T-AO#48]
Caros, 
o sistema de validação online começou a dar um erro no formato do InvoiceNO que no nosso caso deveria estar correcto: FR SED.FR.20/1
Falha na validação do formato do campo AuditFile.SourceDocuments.SalesInvoices.1Invoice.InvoiceNo

Podem ajudar ?

obrigado,
Pedro

**Comment by cacimboerp** [comment]
Tira os caracteres especiais... no caso, os pontos

A quinta, 13/02/2020, 16:48, pcasqueiro <notifications@github.com> escreveu:

**Comment by cryptolopes** [comment]
> Falha na validação do formato do campo AuditFile.SourceDocuments.SalesInvoices.1Invoice.InvoiceNo

O pattern permite a inserção do ponto (.) <xs:pattern value="[^ ]+ [^/^ ]+/[0-9]+" />` pelo que o problema está ao nível do portal da validação.
