### ISSUE TITLE
BuildingAddress não deve ser obrigatorio

### ISSUE THREAD

**Issue by AsrielPires** [assoft-portugal/SAF-T-AO#50]
Na tabela **Customer** o endereço é obrigatorio, mas tem um monte de cituações em que não é possivel se saber a localização do cliente, ex: no caso do Cliente final, ou em estabelecimento como armazens ou bombas que  não parece viavel perguntar ao cliente onde vive.

Mesmo que seja obrigatorio pelo menos deveria aceitar que todos os campos estejam em branco.

**Comment by cryptolopes** [comment]
Pág 5554 do Decreto Presidencial 312/18 https://github.com/assoft-portugal/SAF-T-AO/blob/master/Resources/DP%20312.18%20SAF-T.pdf

Preencher com `Desconhecido`.
