### ISSUE TITLE
Vários erros ao Validar o SAF-T de Aquisições Bens e Serviços

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#51]
Boa tarde,

ao validar um ficheiro SAF-T de Aquisição de bens e serviços ocorrem vários erros, por exemplo:

- O campo AuditFile.SourceDocuments.PurchaseInvoices.Invoice.DocumentTotals.Deductible.DeductibleAmount no ficheiro está na posição errada.

- O campo AuditFile.SourceDocuments.PurchaseInvoices.Invoice.DocumentTotals.Deductible.DeductibleTaxType no ficheiro está na posição errada.

- AuditFile.SourceDocuments.PurchaseInvoices.1Invoice.DocumentTotals.1Deductible.DeductibeAmount é um campo de preenchimento obrigatório

- Formato ou tipo errado do campo AuditFile.SourceDocuments.PurchaseInvoices.1Invoice.DocumentTotals.1Deductible.DeductiblePercentage.

Analisando o  ficheiro .xsd não estou a conseguir perceber onde está o problema!

Será o validador da AGT que tem algum problema?

Envio em anexo um ficheiro SAF-T de exemplo.

[SAFT_STDAOK_01-12-2019_31-12-2019.zip](https://github.com/assoft-portugal/SAF-T-AO/files/4276727/SAFT_STDAOK_01-12-2019_31-12-2019.zip)

Cumprimentos.

**Comment by cryptolopes** [comment]
Olá @MiguelSilva-PBSS 

Schema: https://github.com/assoft-portugal/SAF-T-AO/blob/dev_PurchaseInvoices/XSD/SAFTAO1.01_01.xsd

```bash
$ xmllint --schema XSD/SAFTAO1.01_01.xsd testing/SAFT_STDAOK_01-12-2019_31-12-2019.xml --noout
testing/SAFT_STDAOK_01-12-2019_31-12-2019.xml:6: element TaxRegistrationNumber: Schemas validity error : Element '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}TaxRegistrationNumber': [facet 'minLength'] The value has a length of '9'; this underruns the allowed minimum length of '10'.
testing/SAFT_STDAOK_01-12-2019_31-12-2019.xml:6: element TaxRegistrationNumber: Schemas validity error : Element '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}TaxRegistrationNumber': '123456789' is not a valid value of the atomic type '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}SAFAOAngolaVatNumber'.
testing/SAFT_STDAOK_01-12-2019_31-12-2019.xml fails to validate
```

Para além disso o `AuditFile` não está OK

```xml
<?xml version="1.0" encoding="Windows-1252"?>
<AuditFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="SAF-T_AO">
```

Encoding: `UTF-8`
xmlns: `urn:OECD:StandardAuditFile-Tax:AO_1.01_01`

**Comment by MiguelSilva-PBSS** [comment]
Olá Nelson,

obrigado pela dica.

Corrigindo estes pequenos problemas, o validador da AGT continua a dar os mesmos erros, mas a validação contra o schema passa!

Acho que deve ser um problema do validador!

**Comment by cryptolopes** [comment]
> Acho que deve ser um problema do validador!

Então vai ser necessário uma análise mais em pormenor. Obrigado pelo feedback!

**Comment by anafitas-bamgf** [comment]
Boa tarde Nelson,

Estou com o mesmo problema.
Segue o erro e o ficheiro de testes. 

![image](https://user-images.githubusercontent.com/54372283/75793446-493d7300-5d67-11ea-8a51-bafbb8ea7462.png)


[SAFT_202061_2020630_20200303033945.zip](https://github.com/assoft-portugal/SAF-T-AO/files/4282227/SAFT_202061_2020630_20200303033945.zip)

**Comment by Celso595** [comment]
Também estou com o mesmo problema,parece que o validador trocou o nome  de alguns campos com por exemplo : AuditFile.SourceDocuments.PurchaseInvoices.1Invoice.DocumentTotals.1Deductible.DeductibleAmount .
Se for colocado desta maneira vai passar :AuditFile.SourceDocuments.PurchaseInvoices.1Invoice.DocumentTotals.1Deductible.DeductibeAmount

**Comment by Celso595** [comment]
praticamente existe erro no ficheiro de exemplo que AGT envio. 
![Captura de ecrã de 2020-03-09 13-44-13](https://user-images.githubusercontent.com/61005215/76214060-41208000-620c-11ea-84d7-6ca1f4d20c7f.png)

**Comment by cryptolopes** [comment]
Existe de facto um problema no validador que está a considerar um elemento mal definido.
O elemento chama-se `DeductibleAmount` e não `DedutibleAmount`.
Este problema tem de ser visto ao nível da AGT.

```xml
  <xs:group name="DeductibleTaxes">
    <xs:sequence>
      <xs:element name="Deductible">
        <xs:annotation>
          <xs:documentation>
            Existindo a necessidade de efectuar mais do que uma referência, esta estrutura poderá ser gerada tantas vezes quantas as necessárias.
          </xs:documentation>
        </xs:annotation>  
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TaxBase" type="ns:SAFMonetaryType2DecimalPlaces" />
            <xs:element ref="DeductibleAmount"/>
            <xs:element ref="DeductiblePercentage" />
            <xs:element ref="DeductibleTaxType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
```

**Comment by Zetasoft930** [comment]
O arquivo de arquisição de bens e serviço o modelo a seguir não este que a agt envio?

**Comment by Zetasoft930** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<AuditFile xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:OECD:StandardAuditFile-Tax:AO_1.01_01 https://raw.githubusercontent.com/assoft-portugal/SAF-T-AO/dev_PurchaseInvoices/XSD/SAFTAO1.01_01.xsd">
	<Header>
		<AuditFileVersion>1.01_01</AuditFileVersion>
		<CompanyID>1428854 510310500</CompanyID>
		<TaxRegistrationNumber>5103105000</TaxRegistrationNumber>
		<TaxAccountingBasis>A</TaxAccountingBasis>
		<CompanyName>AGT</CompanyName>
		<BusinessName>Mais AGT</BusinessName>
		<CompanyAddress>
			<AddressDetail>Avenida 4 de Fevereiro</AddressDetail>
			<City>Luanda</City>
			<PostalCode>000</PostalCode>
			<Country>AO</Country>
		</CompanyAddress>
		<FiscalYear>2019</FiscalYear>
		<StartDate>2019-01-01</StartDate>
		<EndDate>2019-12-31</EndDate>
		<CurrencyCode>AOA</CurrencyCode>
		<DateCreated>2019-05-10</DateCreated>
		<TaxEntity>Global</TaxEntity>
		<ProductCompanyTaxID>54173354</ProductCompanyTaxID>
		<SoftwareValidationNumber>0/AGT/2020</SoftwareValidationNumber>
		<ProductID>AGT/AGT</ProductID>
		<ProductVersion>01.01.20</ProductVersion>
	</Header>
	<MasterFiles>
		<Supplier>
			<SupplierID>ADM190</SupplierID>
			<AccountID>Desconhecido</AccountID>
			<SupplierTaxID>1234567890</SupplierTaxID>
			<CompanyName>FORNECEDOR EXEMPLO</CompanyName>
			<BillingAddress>
				<AddressDetail>Morada do Cliente</AddressDetail>
				<City>Luanda</City>
				<Country>AO</Country>
			</BillingAddress>
			<ShipFromAddress>
				<AddressDetail>Morada do Cliente</AddressDetail>
				<City>Luanda</City>
				<Country>AO</Country>
			</ShipFromAddress>
			<SelfBillingIndicator>0</SelfBillingIndicator>
		</Supplier>
		<TaxTable>
			<TaxTableEntry>
				<TaxType>IVA</TaxType>
				<TaxCountryRegion>AO</TaxCountryRegion>
				<TaxCode>NOR</TaxCode>
				<Description>Normal</Description>
				<TaxPercentage>14.000000</TaxPercentage>
			</TaxTableEntry>
			<TaxTableEntry>
				<TaxType>IVA</TaxType>
				<TaxCountryRegion>AO</TaxCountryRegion>
				<TaxCode>ISE</TaxCode>
				<Description>IVA Isento</Description>
				<TaxPercentage>0.00</TaxPercentage>
			</TaxTableEntry>
		</TaxTable>
	</MasterFiles>
	<SourceDocuments>
		<PurchaseInvoices>
			<NumberOfEntries>1</NumberOfEntries>
			
			<Invoice>
				<InvoiceNo>FT 2019A1/12360</InvoiceNo>
				<Hash>ZPi2</Hash>
				<SourceID>ADM</SourceID>
				<Period>5</Period>
				<InvoiceDate>2019-06-09</InvoiceDate>
				<PurchaseType>FT</PurchaseType>
				<SupplierID>ADM190</SupplierID>
				<DocumentTotals>
					<TaxPayable>84000.00</TaxPayable>
					<NetTotal>300000.00</NetTotal>
					<GrossTotal>342000.00</GrossTotal>
					<Deductible>
						<TaxBase>200000.00</TaxBase>
						<DeductibleAmount>28000.00</DeductibleAmount>
						<DeductiblePercentage>100.00</DeductiblePercentage>
						<DeductibleTaxType>OBC</DeductibleTaxType>
					</Deductible>
					<Deductible>
						<TaxBase>100000.00</TaxBase>
						<DeductibleAmount>14000.00</DeductibleAmount>
						<DeductiblePercentage>100.00</DeductiblePercentage>
						<DeductibleTaxType>INV</DeductibleTaxType>
					</Deductible>
					<Currency>
						<CurrencyCode>USD</CurrencyCode>
						<CurrencyAmount>482.27</CurrencyAmount>
						<ExchangeRate>2077.98</ExchangeRate>
					</Currency>
				</DocumentTotals>
				<WithholdingTax>
					<WithholdingTaxType>IVA</WithholdingTaxType>
					<WithholdingTaxDescription>50.00</WithholdingTaxDescription>
					<WithholdingTaxAmount>21000.00</WithholdingTaxAmount>
				</WithholdingTax>
			</Invoice>
			
			<Invoice>
				<InvoiceNo>FT 2019A1/12361</InvoiceNo>
				<Hash>ZPi2</Hash>
				<SourceID>ADM</SourceID>
				<Period>5</Period>
				<InvoiceDate>2019-06-09</InvoiceDate>
				<PurchaseType>FR</PurchaseType>
				<SupplierID>ADM190</SupplierID>
				<DocumentTotals>
					<TaxPayable>84000.00</TaxPayable>
					<NetTotal>300000.00</NetTotal>
					<GrossTotal>342000.00</GrossTotal>
					<Deductible>
						<TaxBase>200000.00</TaxBase>
						<DeductibleAmount>0.00</DeductibleAmount>
						<DeductiblePercentage>0.00</DeductiblePercentage>
						<DeductibleTaxType>OBC</DeductibleTaxType>
					</Deductible>				
				</DocumentTotals>
				<WithholdingTax>
					<WithholdingTaxType>IVA</WithholdingTaxType>
					<WithholdingTaxDescription>0.00</WithholdingTaxDescription>
					<WithholdingTaxAmount>0.00</WithholdingTaxAmount>
				</WithholdingTax>
			</Invoice>
		</PurchaseInvoices>
	</SourceDocuments>
</AuditFile>

**Comment by cryptolopes** [comment]
> O arquivo de arquisição de bens e serviço o modelo a seguir não este que a agt envio?

Sim.

**Comment by Zetasoft930** [comment]
Esse mesmo ficheiro que agt envio não esta a ser validado pelo validador do produtor.está a dar erros de posicionamento das tabs line

**Comment by Zetasoft930** [comment]
tal como mostrei nas imagens acima

**Comment by Zetasoft930** [comment]
Boa tarde gostaria de saber se o problema no validador que está a considerar um elemento mal definido.
O elemento chama-se DeductibleAmount e não DedutibleAmount,já foi retificado?

**Comment by Schobert** [comment]
Também tivemos esse erro de estrutura com a nova estrutura. 
A meu ver, esse erro reportado pelo validador tem a ver com o facto de ele considerar o que está escrito na proposta de alteração da lei, isto é, DeductibeAmount e DeductibeTaxType. ou seja tem uma gralha, porque deveria ser DeductibleAmount** e DeductibleTaxType. Nós testámos em alterando no ficheiro para DeductibeAmount e DeductibeTaxType e então já não retornava esse erro.
Isso deve ser alterado pela AGT asap!

**Comment by cryptolopes** [comment]
@Schobert é um problema que já está endereçado para resolução.

**Comment by RaulKalandula** [comment]
neste caso como ficamos ao tentar validar o SAFT? uma vez em que vcs obrigam.

**Comment by RaulKalandula** [comment]
e també importa realçar k estamos de mãos atada, porque os clientes querem sistemas validados porque a AGT obriga-os

**Comment by nelsonxavier1989** [comment]
Olá pessoa será que podem dar uma ajuda estou com 

o seguinte problema

Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.1Invoice.1Line.1UnitPrice (FR 18XLB-20210113154951/18)
--
Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.1Invoice.1Line.1UnitPrice.1CreditAmount (FR 18XLB-20210113154951/18)
Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.2Invoice.1Line.2UnitPrice (FR 17XLB-20210113154951/17)
Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.2Invoice.1Line.2UnitPrice.2CreditAmount (FR 17XLB-20210113154951/17)
Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.3Invoice.1Line.3UnitPrice (NC 5XLB-20210113154951/5)
Falha na validação do campo AuditFile.SourceDocuments.SalesInvoices.3Invoice.1Line.3UnitPrice.3DebitAmount (NC 5XLB-20210113154951/5)
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.1Invoice.1Line.TaxExemptionReason (FR 18XLB-20210113154951/18) está mal preenchido.
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.2Invoice.1Line.TaxExemptionReason (FR 17XLB-20210113154951/17) está mal preenchido.
Erro no ficheiro, AuditFile.SourceDocuments.SalesInvoices.3Invoice.1Line.TaxExemptionReason (NC 5XLB-20210113154951/5) está mal preenchido.
Erro no ficheiro, AuditFile.SourceDocuments.Payments.1Payment.1Line.TaxExemptionReason (RC 11XLB-20210113154951/11) está mal preenchido.
Erro no ficheiro, AuditFile.SourceDocuments.Payments.2Payment.1Line.TaxExemptionReason (RC 13XLB-20210113154951/13) está mal preenchido.

Já tentei de tudo

Anexei o saft

[REGISTRO Saft F1.zip](https://github.com/assoft-portugal/SAF-T-AO/files/5957576/REGISTRO.Saft.F1.zip)
