### ISSUE TITLE
Erro WithholdingTaxType ao validar um SAF-T de Faturação

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [assoft-portugal/SAF-T-AO#53]
Boa tarde,

ao validar um ficheiro SAF-T de faturação contra o schema obtemos o seguinte erro:

ERROR: Element '{urn:OECD:StandardAuditFile-Tax:AO_1.01_01}WithholdingTaxAmount': This element is not expected. Expected is ( {urn:OECD:StandardAuditFile-Tax:AO_1.01_01}WithholdingTaxType ).

Analisando o decreto este campo não é obrigatório.

Experimentei validar no validador que temos acesso e o ficheiro foi validado com sucesso.

Será que é o schema que está errado ou é um erro da nossa parte?

Segue o ficheiro:
[SAFT_STDAOK_01032020_31032020.zip](https://github.com/assoft-portugal/SAF-T-AO/files/4340026/SAFT_STDAOK_01032020_31032020.zip)

Cumprimentos.

**Comment by cryptolopes** [comment]
> Analisando o decreto este campo não é obrigatório.
> 
> Experimentei validar no validador que temos acesso e o ficheiro foi validado com sucesso.
> 
> Será que é o schema que está errado ou é um erro da nossa parte?

Olá @MiguelSilva-PBSS, 
Com a alteração em 2079885cdf62226bf0166e7901fca7fb76048975 o elemento `WithholdingTaxType` passou a obrigatório.

**Comment by MiguelSilva-PBSS** [comment]
Olá Nelson,

obrigado pelo feedback. 
Entretanto, eu fui verificar a proposta de alteração e o campo continua a não ser obrigatório!

![TaxType](https://user-images.githubusercontent.com/53896958/76846766-ee148180-6838-11ea-8794-990f9dd55763.PNG)

Cumprimentos.

**Comment by cryptolopes** [comment]
@MiguelSilva-PBSS Mas é. Qual é a versão do texto da proposta?

**Comment by MiguelSilva-PBSS** [comment]
Nelson, não encontrei a versão.

Foi nesta proposta que verifiquei:

[Alteração do anexo do Dec. Presidencial 312 compras.pdf](https://github.com/assoft-portugal/SAF-T-AO/files/4342920/Alteracao.do.anexo.do.Dec.Presidencial.312.compras.pdf)

**Comment by cryptolopes** [comment]
@MiguelSilva-PBSS Aqui https://github.com/assoft-portugal/SAF-T-AO/issues/20#issuecomment-567106482

**Comment by MiguelSilva-PBSS** [comment]
Obrigado pelo apoio.

Cumprimentos.

**Comment by MiguelSilva-PBSS** [comment]
Olá Nelson,

estive a analisar melhor esta questão, a obrigatoriedade só está definida para o campo 4.5.2.9.1 da estutura do SAF-T de aquisição de bens e serviços. Não está definida para o campo 4.1.4.21.1 da estutura do SAF-T de faturação.

É para assumir para o campo 4.1.4.21.1 mesmo que não esteja definido na portaria e nem na proposta de alteração?

Cumprimentos.

**Comment by cryptolopes** [comment]
@MiguelSilva-PBSS Olá, como estás?
Sim, estamos só a aguardar a publicação do despacho para tornar definitivas as alterações. O elemento WithholdingTax passa a constar como referência em todos os casos.
