### ISSUE TITLE
Sistema para validação do SAFT-AO.

### ISSUE THREAD

**Issue by EloneSampaio** [assoft-portugal/SAF-T-AO#54]
Tenho meu xml criado e validei o arquivo com o (xmllint) agora queria saber se existe alguma plataforma da (AGT) que permite validar o arquivo ?  Pra eu ter certeza que está tudo certo antes de colocar a funcionalidade em produção.

**Comment by EloneSampaio** [comment]
já achei, o endereço eletronico tinha sido alterado. para quem precisar esse é o novo link 
https://portaldocontribuinte.minfin.gov.ao/

**Comment by cryptolopes** [comment]
@EloneSampaio 👍
