### ISSUE TITLE
Erro ao validar saftao.XML no portal

### ISSUE THREAD

**Issue by lutonda** [assoft-portugal/SAF-T-AO#55]
**Describe your question**

A clear and concise description of what the question is.

Bom dia, estou tendo esse erro ao tentar validar o ficheiro xml pelo portal,

- . Alguém tem uma ideia de que se trata ou qual a origem deste Erro:
```Existem erros de sintaxe xml no ficheiro (Falha validação xsd)```
![image](https://user-images.githubusercontent.com/1699809/76927691-fbd11200-68df-11ea-8c4b-a993d051fcb5.png)

Nota: Noutras validações pare tudo bem e este erro nao aprece, (Pelo terminal usando *xmllint* ou no meu metodo psefl validation* que uso dentro da minha aplicação)
- . Alguem sabe como validar ate o Hash do satfao.xml com o ficheiro XSD?

**Comment by cryptolopes** [comment]
@lutonda Bom dia!
Indique, por favor, qual é a versão do XSD que está a usar.
Se possível, anexe aqui o XML.

**Comment by lutonda** [comment]
Aparentemente estou usando a versão 1.01_01.0.006
[SAFTAO1.01_01.zip](https://github.com/assoft-portugal/SAF-T-AO/files/4352777/SAFTAO1.01_01.zip)

**Comment by cryptolopes** [comment]
@lutonda 
Essa é a última Pré-Release criada. Essa versão ainda não contempla a proposta de alteração à estrutura de compras (https://github.com/assoft-portugal/SAF-T-AO/issues/20#issuecomment-567106482). 

Está alguns commits atrás: https://github.com/assoft-portugal/SAF-T-AO/compare/1.01_01.0.006...dev_PurchaseInvoices

Recomendamos, que até à criação de uma nova Release, usem o schema que está disponível diretamente a partir do diretório.

**Comment by cryptolopes** [comment]
#20

**Comment by lutonda** [comment]
Mas no entanto nao entendi muito bem a origem do erro que estou tendo no portal da AGT
````Existem erros de sintaxe xml no ficheiro (Falha validação xsd) ````

**Comment by cryptolopes** [comment]
@lutonda 

> Mas no entanto nao entendi muito bem a origem do erro que estou tendo na ferramenta de validação do portal da AGT
> `Existem erros de sintaxe xml no ficheiro (Falha validação xsd) `

Quer dizer que existem erros de estrutura. O XML não é válido.

**Comment by lutonda** [comment]
OK!
Obrigado
