### ISSUE TITLE
Existe algum tutorial?

### ISSUE THREAD

**Issue by balduinofernando** [assoft-portugal/SAF-T-AO#56]
Existe algum tutorial sobre como implementar essa Biblioteca?
Já verifiquei as Issues, as Wiki deste repositório e ainda assim não há nenhum lugar que indique como fazer a implementação da mesma.

Agradecia muito a ajuda de quem já fez, trabalho com PHP (Laravel) e qualquer ajuda relacionada será apreciada, se for muito extenso, o meu email é [bafernando94@gmail.com](bafernando94@gmail.com).

**Comment by cryptolopes** [comment]
@balduinofernando 

Tente esta: https://www.php.net/xml

**Comment by Zecaspider** [comment]
Bom dia, sou novo por aqui, e estou a enfrentar as mesmas dificuldades que o @balduinofernando . Tenho uma aplicação de gestão escolar e cobrança de propinas, e se pretende certificar o modulo de pagamento de propinas junto a AGT. A minha aplicação está em Java com PlayFramework 1.5.
se alguém souber de um PONTO de partida que me possa indicar, ficaria eternamente grato.

**Comment by cryptolopes** [comment]
@Zecaspider https://www.tutorialspoint.com/java_xml/index.htm
