### ISSUE TITLE
Reposição do elemento SelfBillingIndicator conforme original

### ISSUE THREAD

**Issue by ruimlneves** [assoft-portugal/SAF-T-AO#57]
Olá.

Mais alguém está com este problema?
Quando incluímos no SAFT um documento com cativação de IVA que, segundo o XSD, deve ir `<SelfBillingIndicator>2</SelfBillingIndicator>`, obtemos a seguinte mensagem:

Formato ou tipo errado do campo AuditFile.SourceDocuments.SalesInvoices.26Invoice.SpecialRegimes.SelfBillingIndicator

No XSD, a especificação é:
```
<xs:element name="SelfBillingIndicator">
    <xs:annotation>
      <xs:documentation>
        PROPOSTA:
        Deve ser preenchido:
        com “1” se respeitar a autofacturação,
        Com “2” se é obrigado a cativar o IVA,
        Com ”3” se tiver IVA cativo e autofacturação,
        com “0” (zero) no caso de não cumprir com nenhuma condição .
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
        <xs:maxInclusive value="3" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
```
 se enviarmos com o valor 0 ou 1 não dá qualquer problema.

Obrigado

**Comment by cryptolopes** [comment]
Ola @ruimlneves 
Ao submeter no [Portal do Contribuinte](https://agt.minfin.gov.ao/PortalAGT/)?

**Comment by ruimlneves** [comment]
> Ola @ruimlneves
> Ao submeter no [Portal do Contribuinte](https://agt.minfin.gov.ao/PortalAGT/)?

Sim

**Comment by cryptolopes** [comment]
@ruimlneves Tal como descrito parece estar bem. São necessários  mais esclarecimentos da AGT em relação a isso. Possivelmente o Luís pode dar mais alguma ajuda.

**Comment by cryptolopes** [comment]
# Reposição do elemento SelfBillingIndicator conforme original

Em setembro de 2019 foi introduzida a proposta de alteração do elemento `SelfBillingIndicator` para aceitar os valores `2` e `3`, que passou a suportar o **Regime de IVA Cativo**. Este elemento foi inicialmente concebido para identificar documentos emitidos ao abrigo apenas ao abrigo do **Regime de Autofaturação**.

Esta alteração foi introduzida no schema no commit d7e4b0a579cdd97d91d18d7f6621b51d201017f5.

https://github.com/assoft-portugal/SAF-T-AO/blob/50cbc25986e9875335ba28b8165aeea79fdd825d/XSD/SAFTAO1.01_01.xsd#L1426-L1444

Mais recentemente, com a [Proposta de alteração da estrutura PurchaseInvoices](https://github.com/assoft-portugal/SAF-T-AO/issues/20#issuecomment-567106482) (estrutura de compras), passou a ser possível indicar os documentos sujeitos ao Regime de IVA Cativo através do elemento `WithholdingTax`.

O reporte de **imposto cativo** é agora semelhante ao de uma **retenção**, mais simples e transparente para todos. Aplica-se aos documentos do tipo Fatura, Nota de Crédito, Recibo e de Compra.

Esta alteração foi introduzida no schema no commit 2079885cdf62226bf0166e7901fca7fb76048975.

https://github.com/assoft-portugal/SAF-T-AO/blob/50cbc25986e9875335ba28b8165aeea79fdd825d/XSD/SAFTAO1.01_01.xsd#L1562-L1583

https://github.com/assoft-portugal/SAF-T-AO/blob/50cbc25986e9875335ba28b8165aeea79fdd825d/XSD/SAFTAO1.01_01.xsd#L702-L706

# Proposta de alteração

Com as alterações recentes deixa de ser necessário o recurso ao elemento `SelfBillingIndicator`, podendo este ser resposto tal e qual como existia originalmente.

https://github.com/assoft-portugal/SAF-T-AO/blob/e3c1854b8dfe6735f74aef91fc8c14e674467627/XSD/SAFTAO1.01_01.xsd#L1297-L1305

# Processo de decisão

Considerando que já se passou algum tempo desde a primeira alteração, queremos saber a opinião dos fabricantes sobre se estão de acordo com esta alteração de repor o elemento `SelfBillingIndicator` conforme original.

## Votação

Vote [**aqui**](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=ansj7KEmtk-EmgVkqBloMhe9y-bzE4hHn0xdj7GSEphUMjBITTZVMDI3MkU5SkJGVDhDSktMS1hXSSQlQCN0PWcu) até **quinta-feira, dia 26 de março** e deixe os seus comentários em baixo.
