### ISSUE TITLE
Payments declarados como recibo RC

### ISSUE THREAD

**Issue by Marcosinffoco** [assoft-portugal/SAF-T-AO#59]
**Payments declarados como recibo RC**

Na minha ultima reunião de avaliação do sistema para certificação final, exibi o meu modelo de recibo, pois o técnico da AGT tinha pedido para mostrar.

**Numero do Recibo - Modelo do meu sistema : RC RE20/3**

**RC - RECIBO EMITIDO**
É o tipo de documento declarado nesta parte do SAFT AO - Payments - PaymentType

Na arquitectura do sistema, declarei todos os recibos somente nesta parte do SAFT.

Não declaro recibos em SourceDocuments - SalesInvoices.

Pois na minha óptica, o cliente pode liquidar vários documentos (facturas) com um (único) pagamento, por isto que a parte declarada em Payments é encaixado perfeitamente, de acordo com o meu controle de conta corrente.

O técnico da AGT me informou que declarasse como RE - RECIBO, mas este tipo (InvoiceType) em 
 SourceDocuments - SalesInvoices.

**Acho que estou procedendo perfeitamente, por que RE não esta listado como um PaymentType em  Payments - PaymentType**

**Imagino, de acordo com a aquitectura, estou declarando perfeitamente**

Alguém aqui, já passou por esta questão?

Estou aberto a sugestões

**Comment by cryptolopes** [comment]
@Marcosinffoco Olá!
E está a fazer bem. Os recibos devem ser reportados no elemento Payments. Deve ter-se tratado de um lapso, pois o elemento InvoiceType com o valor RE aplica-se apenas ao setor segurador.

https://github.com/assoft-portugal/SAF-T-AO/blob/112214948c683a491ad2b7f404930269e417e929/XSD/SAFTAO1.01_01.xsd#L1809-L1823

**Comment by cryptolopes** [comment]
Olá!
E está a fazer bem. Os recibos devem ser reportados no elemento `Payments`. Deve ter-se tratado de um lapso, pois o elemento `InvoiceType` com o valor `RE` aplica-se apenas ao setor segurador.

https://github.com/assoft-portugal/SAF-T-AO/blob/112214948c683a491ad2b7f404930269e417e929/XSD/SAFTAO1.01_01.xsd#L1809-L1823

**Comment by Marcosinffoco** [comment]
Cryptolopes..   muito obrigado pelo esclarecimento.   No dia da minha reunião para a certificação, vi que colocavam questões para pegar as falhas no sistema. como por exemplo tentar emitir uma factura com data anterior a ultima emitida.   Vi nos olhos da técnica que queria me pegar neste ponto, mas já sabia o que iria acontecer.  Ainda bem que consegui prever estes tipos de critérios.

**Comment by cryptolopes** [comment]
@Marcosinffoco 
Testes de conformidade também é isso.

**Comment by Adriiano** [comment]
Como é possível emitir recibo com duas taxa iva
14% (Normal)
0% (Isento)

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments).
1 - Na minha factura (FT) têm duas linhas.

      <LineNumber>1</LineNumber>
     <CreditAmount>100000.00</CreditAmount>
     <TaxPercentage>14</TaxPercentage>
   
     <LineNumber>2</LineNumber>
     <CreditAmount>50000.00</CreditAmount>
     <TaxPercentage>0</TaxPercentage>


Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by cryptolopes** [comment]
> Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

Sim, é possível. Agrupam-se os valores por cada base de incidência.
