### ISSUE TITLE
DateCreated - Verifica se data de fim do ficheiro é menor ou igual à data de criação

### ISSUE THREAD

**Issue by Marcosinffoco** [assoft-portugal/SAF-T-AO#61]
**No Validador temos esta mensagem**

**Ficheiro AuditFile.Header.DateCreated - Verifica se data de fim do ficheiro é menor ou igual à data de criação**

Declarei da seguinte forma:

```xml
	<FiscalYear>2020</FiscalYear>
	<StartDate>2020-03-01</StartDate>
	<EndDate>2020-03-31</EndDate>
	<CurrencyCode>AOA</CurrencyCode>
	<DateCreated>2020-04-06</DateCreated>
```

Chequei que em todos os documentos, não há nenhum fora do intevalo do periodo StartDate e EndDate.

O primeiro documento começa com 2020-03-13 e termina com 2020-03-26.

O campo DateCreated, imagino eu, que é somente a data que foi criado o XML - SAFT AO.

Que pela lógica, pode ser datas posteriores ao mês pesquisado.

Notei isto apartir da declaração do mês de fevereiro.

Até imaginei que era por ser o ano Bissexto e o validador não reconhecia o dia 29/02/2020.
Como devemos proceder.

**Comment by cryptolopes** [comment]
@Marcosinffoco 
Este problema já está endereçado para resolução.
