### ISSUE TITLE
Geração chave HASH do SAF-T-AO

### ISSUE THREAD

**Issue by vd-king** [assoft-portugal/SAF-T-AO#63]
Boa tarde caríssimos,

Pretendo algumas dicas de como encriptar os dados usando a criptografia RSA, quando o tamanho do dado a encriptar é superior ao tamanho da chave (1024), e garantir que o texto encriptado não passe dos 172 bytes, usando a aplicação OpenSSL corre bem, mais a usar o C#, ou o VB.NET me deparo com a dificuldade acima exposta. 

Osvaldo Mateus

**Comment by cryptolopes** [comment]
Duplicate of #49

**Comment by FernandoManuel6107** [comment]
> Boa tarde caríssimos,
> 
> Pretendo algumas dicas de como encriptar os dados usando a criptografia RSA, quando o tamanho do dado a encriptar é superior ao tamanho da chave (1024), e garantir que o texto encriptado não passe dos 172 bytes, usando a aplicação OpenSSL corre bem, mais a usar o C#, ou o VB.NET me deparo com a dificuldade acima exposta.
> 
> Osvaldo Mateus

Saudações Caríssimo,

Nesse momento estou com o mesmo problema com que estás.

Gostaria de saber se já encontrou alguma solução.
