### ISSUE TITLE
Certificação de Software em Angola

### ISSUE THREAD

**Issue by FMACC1** [assoft-portugal/SAF-T-AO#64]
Boa tarde,

Alguém que já tenha feito a certificação do software na AGT, pode pff dar algum input sobre o processo?

Como se despoleta? Como decorre? Como podemos validar o ficheiro SAFT que estamos a desenvolver?

Obrigado desde já,
Filipe

**Comment by vd-king** [comment]
Boa noite caríssimo, 
por acaso estou no mesmo processo, 

1. aceder o portal [https://invoice.minfin.gov.ao/portalSupplier/views/login/login.html](url), 
2. Efectuar o cadastro
3. Efectuar uma Solicitação de Validação do Software Comercial
4. aguardar pelo pronunciamento da AGT

**Comment by FMACC1** [comment]
Boa noite,

Muito obrigado!

Em termos de processo, sabe se é necessário fazer uma demonstração à AGT? 
A estrutura do SAFT pode ser validado, nesse link que me enviou? 

Obrigado
Filipe

**Comment by vd-king** [comment]
@FMACC1, sei que é necessário fazer essa demonstração sim, no email terá essa informação, no link que enviei depois de efectuar o cadastro terá sim como testar o saft.
no meu caso estou a terminar o saft, mais estou com dificuldades em trabalhar com o RSA, conhece algum site onde posso encontrar informações a respeito ou exemplo de códigos, que funcionem tal como o openssl?

**Comment by FMACC1** [comment]
Ainda estou no início do processo, ainda não investiguei essa parte.

Mas veja este tópico: https://github.com/assoft-portugal/SAF-T-AO/issues/49

Pode ser que alguém o ajude.

**Comment by juliaokataleko** [comment]
> @FMACC1, sei que é necessário fazer essa demonstração sim, no email terá essa informação, no link que enviei depois de efectuar o cadastro terá sim como testar o saft. no meu caso estou a terminar o saft, mais estou com dificuldades em trabalhar com o RSA, conhece algum site onde posso encontrar informações a respeito ou exemplo de códigos, que funcionem tal como o openssl?



> Boa noite caríssimo, por acaso estou no mesmo processo,
> 
> 1. aceder o portal [https://invoice.minfin.gov.ao/portalSupplier/views/login/login.html](url),
> 2. Efectuar o cadastro
> 3. Efectuar uma Solicitação de Validação do Software Comercial
> 4. aguardar pelo pronunciamento da AGT

Olá família. Também estou nesta luta!!
Os requisitos se mantêm os mesmos??

E como é o processo da assinatura digital nas facturas?
SE poderem me ajudar, agradeço imenso.

**Comment by domingosnngunza** [comment]
2025........ Terminei o saft testei.. me mandaram um email : vsiva.dsiva.agt.@minfin.gov.ao.. infelizmente estava a dar email invalido. alterei o email retirando o ponto antes do @ e foi  mas ate agora nada ........._??? alguem ai consegui

**Comment by D-Baptista** [comment]
> 2025........ Terminei o saft testei.. me mandaram um email : [vsiva.dsiva.agt.@minfin.gov.ao](mailto:vsiva.dsiva.agt.@minfin.gov.ao).. infelizmente estava a dar email invalido. alterei o email retirando o ponto antes do @ e foi mas ate agora nada ........._??? alguem ai consegui

Estou nisso desde Janeiro, já fiz tudo, mas não recebi nenhuma resposta ainda.

**Comment by katalekoweb** [comment]
> > 2025........ Terminei o saft testei.. me mandaram um email : [vsiva.dsiva.agt.@minfin.gov.ao](mailto:vsiva.dsiva.agt.@minfin.gov.ao).. infelizmente estava a dar email invalido. alterei o email retirando o ponto antes do @ e foi mas ate agora nada ........._??? alguem ai consegui
> 
> Estou nisso desde Janeiro, já fiz tudo, mas não recebi nenhuma resposta ainda.

Estou nessa luta também. Estou quase a terminar meu software. Precisa ter NIF activo para enviar o sistema na avaliação da AGT não é???

**Comment by D-Baptista** [comment]
> > > 2025........ Terminei o saft testei.. me mandaram um email : [vsiva.dsiva.agt.@minfin.gov.ao](mailto:vsiva.dsiva.agt.@minfin.gov.ao).. infelizmente estava a dar email invalido. alterei o email retirando o ponto antes do @ e foi mas ate agora nada ........._??? alguem ai consegui
> > 
> > 
> > Estou nisso desde Janeiro, já fiz tudo, mas não recebi nenhuma resposta ainda.
> 
> Estou nessa luta também. Estou quase a terminar meu software. Precisa ter NIF activo para enviar o sistema na avaliação da AGT não é???

Sim. Tem que ser um NIF comercial.

**Comment by adilsonxavierfernando** [comment]
Onde se faz o teste do saft? Tem de seguir protocolos específicos? Tipo
escrever requerimentos e tal?

A quinta, 24/04/2025, 01:25, D. Baptista ***@***.***>
escreveu:

**Comment by domingosngunnza** [comment]
Alguem conseguio licenciar software este ano??' Boa tarde a todos

**Comment by katalekoweb** [comment]
> > > > 2025........ Terminei o saft testei.. me mandaram um email : [vsiva.dsiva.agt.@minfin.gov.ao](mailto:vsiva.dsiva.agt.@minfin.gov.ao).. infelizmente estava a dar email invalido. alterei o email retirando o ponto antes do @ e foi mas ate agora nada ........._??? alguem ai consegui
> > > 
> > > 
> > > Estou nisso desde Janeiro, já fiz tudo, mas não recebi nenhuma resposta ainda.
> > 
> > 
> > Estou nessa luta também. Estou quase a terminar meu software. Precisa ter NIF activo para enviar o sistema na avaliação da AGT não é???
> 
> Sim. Tem que ser um NIF comercial.

Será que o NIF pode ser de comerciante em nome individual?? os outros tipos estão a exigir contabilista, são mais gastos.
