### ISSUE TITLE
Elemento SourceDocuments | MovementOfGoods: AGTDocCodeID

### ISSUE THREAD

**Issue by batalhadematos** [assoft-portugal/SAF-T-AO#68]
Estimados,

Boa tarde a todos.
No XSD existe um elemento que não consta da estrutura 318/12 que é o '**AGTDocCodeID**' em _SourceDocuments | MovementOfGoods_.

Deparei-me com um apontamento meu sobre esse novo elemento e ao testar o xml contra o XSD actualizado, noto que é um elemento obrigatório.

Alguém pode por gentileza me explicar que informação deve ser colocada neste elemento?

Aproveito para perguntar se esse elemento já é validado pelo portal de testes do produtor?

Obrigado a todos e até breve

Paulo Matos

**Comment by cryptolopes** [comment]
> No XSD existe um elemento que não consta da estrutura 318/12 que é o '**AGTDocCodeID**' em _SourceDocuments | MovementOfGoods_.
> 
> Deparei-me com um apontamento meu sobre esse novo elemento e ao testar o xml contra o XSD actualizado, noto que é um elemento obrigatório.

O elemento **não é** obrigatório:

https://github.com/assoft-portugal/SAF-T-AO/blob/600212f8bf329447b04b01d610d8de28ed63162c/XSD/SAFTAO1.01_01.xsd#L475-L476

**Comment by batalhadematos** [comment]
@cryptolopes Obrigado Nelson.
Provavelmente o erro gerado foi de outro elemento e como estava a ver este não prestei atenção. 
Contudo, se possivel seria importante ter uma descrição sobre que informação colocar neste elemento.

Até breve

**Comment by cryptolopes** [comment]
> se possivel seria importante ter uma descrição sobre que informação colocar neste elemento

É para ter um comportamento semelhante ao que se sucede com a AT em Portugal. Consiste no código de resposta para autorização do documento de transporte. Neste momento ainda não existe enquadramento para a sua utilização.

**Comment by batalhadematos** [comment]
@cryptolopes Hummmm. Ok. Valeu @nelsonlopes. Obrigado mais uma vez
