### ISSUE TITLE
Ajuda sobre o elemento SalesInvoices | SourceBilling

### ISSUE THREAD

**Issue by batalhadematos** [assoft-portugal/SAF-T-AO#69]
Estimados,

Boa tarde,
Preciso da vossa ajuda na correcta interpretação do campo: SalesInvoices | **SourceBilling**

> Deve ser preenchido com:
> P - Documento produzido na aplicação
> I - Documento integrado e produzido noutra aplicação
> M - Documento proveniente de recuperação ou emissão manual

No caso, a minha dúvida se refere a um módulo de "mobilidade" da nossa aplicação e que, mesmo que não precise funcionar de forma integrada, pertence à mesma aplicação.

A diferença é que funciona sem precisar estar permanentemente ligada à aplicação principal para emissão de documentos.

A integração é feita à pedido do utilizador ou em momentos específicos, como por exemplo no momento de descarregar dados para a aplicação principal.

Neste caso que opção deverei escolher, "P" (**mesma aplicação**) ou "I" (**integrado e produzido em outra aplicação**"? 

Obrigado e até breve

PM

**Comment by cryptolopes** [comment]
> Preciso da vossa ajuda na correcta interpretação do campo: SalesInvoices | **SourceBilling**

`P` para documento produzido na aplicacao:

- documentos criados dentro do ecossistema da mesma aplicação validada
- criados pela aplicação
- criados por interfaces da aplicação, como são P.O.S. ou soluções de mobilidade

`I` para documento integrado e produzido noutra aplicacao,

- documentos criados por outra solução validada, integrados na aplicação na solução principal
- criados noutras aplicações concorrentes
 
`M` para documento proveniente de recuperacao ou de emissao manual

- documentos que também são integrados, mas que têm origem em documentos pré-impressos~
- faturas ou notas de crédito pré-impressas
