### ISSUE TITLE
Elementos TaxPayable, NetTotal e GrossTotal dos RECIBOS

### ISSUE THREAD

**Issue by batalhadematos** [assoft-portugal/SAF-T-AO#70]
Estimados,

Boa noite a todos.
Preciso da vossa ajuda para entender melhor a estrutura do elemento **DocumentTotals** dos Recibos em SAF-T.

Nesta estrutura, existem dois elementos que pela sua descrição deixaram-me com dúvidas sobre como preencher. Estes são:

> - "TaxPayable": Valor do Imposto a Pagar;
> - "NetTotal": "Este campo não deve incluir as parcelas referente aos impostos contantes da tabela 2.5 - Tabela de Impostos (TaxTable);

Depreendo que aqui nos referimos aos impostos constante do documento que deu origem ao Recibo (Factura, Nota de Crédito...)

Vou deixar dois exemplos e espero que me possam ajudar.

**1. Factura com 1000 AOA c/ IVA a 14%.**

Total da Factura s/IVA: 1000.00
Total da Factura c/IVA: 1140.00

Com base nestes dados, os elementos TaxPayable e NetTotal do Recibo deverão ser preenchidos com:

**- TaxPayable:** 140.00
**- NetTotal:** 1000.00
**- GrossTotal:** 1000 (assumindo que não existem retenções na fonte)

Isto está correcto?

2. Usando agora o mesmo exemplo, mas com pagamentos parciais da mesma factura, usando para isso 2 recibos de 570.00 kz cada um.

2.1 Recibo Nº1: 570.00 kz

**- TaxPayable:** --- que valor deverá ser incluído aqui? O valor total do imposto incluído na factura (140.00) ou a proporção referente ao imposto com base no pagamento registado (70.00)? 
**- NetTotal:**  500.00

2.2 Recibo Nº2: 570.00 Kz

**- TaxPayable:** --- o mesmo para este recibo
**- NetTotal:** 500.00

Procurei pelos issues e não encontrei uma resposta a esta minha dúvida.
Encontrei um exemplo de um XML de Recibo, mas não posso me basear neste porque não conheço os valores da factura a que se refere o recibo de exemplo.

O exemplo está [AQUI](https://github.com/assoft-portugal/SAF-T-AO/issues/38#issuecomment-557149884)

Obrigado a todos e continuação de bom fim de semana

PM

**Comment by cryptolopes** [comment]
@batalhadematos 

Nos recibos não existe a obrigatoriedade de criar o regime de impostos, com exceção do Regime de IVA de Caixa. A inclusão da tabela de impostos obviamente que complica o processo quando existem pagamentos parciais.

**Comment by batalhadematos** [comment]
@cryptolopes Obrigado @nelsonlopes. Era precisamente esta a dúvida e umas das alternativas só faria sentido em caso de regimes de IVA de caixa precisamente pela distribuição do IVA pelos pagamentos parciais. 
Obrigado mais uma vez. Abraço

**Comment by Schobert** [comment]
@cryptolopes 

Eu vi que está fechado o issue, mas queria comentar:
"Nos recibos não existe a obrigatoriedade de criar o regime de impostos, com exceção do Regime de IVA de Caixa."

Nelson, queres dizer com isso que nos recibos "normais" (não IVA de caixa) não é obrigatório reportar a informação de IVA?
Em tempos também abordei essa questão porque também tinha essa interpretação, mas não é essa a resposta que tenho da parte da AGT.

Ou interpretei mal a tua resposta?

**Comment by cryptolopes** [comment]
> Nelson, queres dizer com isso que nos recibos "normais" (não IVA de caixa) não é obrigatório reportar a informação de IVA?

Olá @Schobert,
No início houve alguma discussão sobre este assunto, na medida em que a AGT entendia que a estrutura `Payments` devia comportar os elementos relativos aos impostos tal e qual como acontece nos elementos da estrutura `SalesInvoices`. Após se ter discutido isso e se terem mostrado as alternativas e as possibilidades à volta dos Payments, tais como um único recibo poder dizer respeito a vários documentos de venda ou até a pagamentos parciais, foi decidido aceitar documentos sem a parte referente ao imposto. Este aspeto é aliás permitido pelo schema desde o início.

**Comment by Schobert** [comment]
Olá outra vez, @cryptolopes Nelson. 
Foi decidido? por quem, quando, foi divulgado? 
a meu ver não basta o schema deixar ou não deixar, as regras têm de ser explícitas, não implícitas, as notas técnicas servem para isso. 
Quer dizre que podemos eliminar toda a informação do IVA que reportamos nos Recibos?

**Comment by AfonsoMenata** [comment]
Boa noite, Caríssimos;

Eu acredito que este assunto é sério e a AGT deveria tratar dele com grande preocupação.Porque:
Cadas recibo, está ligado à uma factura. Logo, ao emitir um recibo, os dados do imposto, já foram relatados no SAFT, à quando da emissão da factura.
A AGT quer saber dos imposto, referentes aos reccibos? Então que ela olhe para as referidas facturas que deram lugar aos recibo.
Pois, ao colocar a extrutura de impostos (Côdigo do tipo de impostos, Motivo de isenção, taxa de impostos e outros) nos pagamentos (Paymentes), passa a ideia de que ao emitir um recibo, a empresa cobra um novo IVA, para além do IVA acordade nas facturas. Esta é a minha opinião.

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments).
1 - Na minha factura (FT) têm duas linhas.

      <LineNumber>1</LineNumber>
     <CreditAmount>100000.00</CreditAmount>
     <TaxPercentage>14</TaxPercentage>
   
   <LineNumber>2</LineNumber>
     <CreditAmount>50000.00</CreditAmount>
     <TaxPercentage>0</TaxPercentage>
Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments).
1 - Na minha factura (FT) têm duas linhas.

      <LineNumber>1</LineNumber>
     <CreditAmount>100000.00</CreditAmount>
     <TaxPercentage>14</TaxPercentage>
   
   <LineNumber>2</LineNumber>
     <CreditAmount>50000.00</CreditAmount>
     <TaxPercentage>0</TaxPercentage>

Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by Adriiano** [comment]
Olá!
Tenho grandes dificuldades na emissão de recibo (Payments).
1 - Na minha factura (FT) têm duas linhas.

      <LineNumber>1</LineNumber>
     <CreditAmount>100000.00</CreditAmount>
     <TaxPercentage>14</TaxPercentage>
   
     <LineNumber>2</LineNumber>
     <CreditAmount>50000.00</CreditAmount>
     <TaxPercentage>0</TaxPercentage>


Será que na emissão do meu recibo tenho que adicionar também as duas linhas?

**Comment by cryptolopes** [comment]
https://github.com/assoft-portugal/SAF-T-AO/issues/59#issuecomment-1497500550
