### ISSUE TITLE
Deduções Regime Geral

### ISSUE THREAD

**Issue by batalhadematos** [assoft-portugal/SAF-T-AO#71]
Estimados,

Bom dia a todos.
Tenho algumas questões sobre as deduções do IVA no regime geral e espero que me possam ajudar.

1. Taxa de Dedução (DeductiblePercentage): Este valor é fixo ou variável? Se variável, de que depende (tipo de actividade, DeductibleTaxType...)?

2. Refere-se que existem operações isentas que "conferem" direito a dedução e operações isentas que "não conferem" direito a dedução.

Sendo que os direitos a dedução estão relacionados ao processo de aquisição de bens e serviços, alguém pode me esclarecer e se possivel com um exemplo de como em uma operação isenta, existirá direito a dedução (que confere direito a dedução)?

Obrigado a todos

Até breve

Paulo Matos

**Comment by cryptolopes** [comment]
> Taxa de Dedução (DeductiblePercentage): Este valor é fixo ou variável? Se variável, de que depende (tipo de actividade, DeductibleTaxType...)?

Variável

> existirá direito a dedução (que confere direito a dedução)?

É uma dúvida mais sobre IVA.

**Comment by batalhadematos** [comment]
Viva @cryptolopes,
Sim. Trata-se de questões relacionadas mesmo às deduções do IVA (compras).
No primeiro caso, todos os exemplos e informação que encontro, referem deduções de 100%, já no segundo é mais um problema meu em interpretar a lei e precisava de um esclarecimento de alguém mais "bem preparado" nesta área.
Abraço
Paulo Matos
