### ISSUE TITLE
Regime Transitório e Deduções

### ISSUE THREAD

**Issue by batalhadematos** [assoft-portugal/SAF-T-AO#72]
Estimados,

Bom dia a todos.
Tenho algumas questões sobre a aplicabilidade do IVA no Regime Transitório e espero que me possam ajudar.

Inicialmente estava previsto que:
1. Não há liquidação de IVA nas facturas, mas há entrega de IVA ao estado - o correspondente a metade do IVA (trimestralmente) sobre as operações recebidas (excluindo as isentas).
2. Possibilidade de Dedução de até 4% do IVA suportado das aquisições
3. As regras para dedução do imposto são as mesmas aplicadas ao regime geral (excepto a percentagem)

Esta situação mantém-se ou foi alterada?

Obrigado a todos mais uma vez

Paulo Matos

**Comment by cryptolopes** [comment]
@batalhadematos 

Para esse tipo de questões, como não têm diretamente que ver com o SAF-T, sugiro que use o [grupo no Telegram](https://t.me/saftao).

**Comment by batalhadematos** [comment]
Obrigado @cryptolopes 
Como tenho a conta do github ligada ao Telegram, sabia que ia parar lá também e dependendo da resposta pode estar relacionada ao SAF-T (das compras pelo menos).
O problema é que houve algumas alterações à Lei e não sei se esta parte também foi alterada.
Abraço
