### ISSUE TITLE
DeductiblePercentage requer taxa do imposto? 

### ISSUE THREAD

**Issue by Schobert** [assoft-portugal/SAF-T-AO#73]
Presentemente, o validador dos produtores de SW, exige para o Ficheiro Tipo A (Purchase), que o campo <DeductiblePercentage>indique a percentagem da taxa do IVA dedutível, por exemplo, 14.00, e não a percentagem do que é dedutível, por exemplo 100.00. 

Isto é uma alteração ao comportamento ao validador. No entanto a proposta de alteração da Lei e o XSD não sofreram nenhuma alteração neste campo. De

Isto é para ficar assim, devemos interpretá-lo de forma diferente a partir de agora?

Agradeço esclarecimento.

**Comment by cryptolopes** [comment]
@Schobert Devia ser a:
> percentagem do que é dedutível, por exemplo 100.00

podes ajudar Luís?

**Comment by cryptolopes** [comment]
Esta situação foi ultrapassada @Schobert?
E, se sim, qual foi a solução?

**Comment by Schobert** [comment]
Ultrapassado.
solução: DeductiblePercentage deve conter a percentagem da medida em que o imposto é dedutível. 
exemplo: 
IVA 14%, totalmente dedutível ==> DeductiblePercentage = 100
IVA 14%, não dedutível ==> DeductiblePercentage = 0
