### ISSUE TITLE
Portal de Validação do SAFT-AO

### ISSUE THREAD

**Issue by reactor-gonguela** [assoft-portugal/SAF-T-AO#76]
Erro ao aceder o portal de validação da agt

Não consigo aceder ao portal de validação do ficheiro SAFT. 
Mais alguem tem o mesmo problema? 
Alguem sabe porque razão o portal não funciona? e quando reestabelece?

Estou a usar o endereço:
https://invoice.minfin.gov.ao

**Comment by cryptolopes** [comment]
@reactor-gonguela https://t.me/saftao/1322
