### ISSUE TITLE
Outras fontes sobre esclarecimento da implementação do Saft

### ISSUE THREAD

**Issue by sebastiao39** [assoft-portugal/SAF-T-AO#79]
Boa tarde pessoal!. Talvez não esteja fazendo a pergunta no local certo, mas gostaria que me apresentassem outras fontes onde abordam sobre a implementação do SAFT como whattssap ou outras redes sociais de modo que consiga obter mais informções sobre o saft ou as dificuldades que encontramos durante a implementação.
Obrigado

**Comment by cryptolopes** [comment]
@sebastiao39 1. Yammer (SAF-T AO)
2. Grupo no Telegram
