### ISSUE TITLE
Tag CUD não está considerada.

### ISSUE THREAD

**Issue by RMSInforap** [assoft-portugal/SAF-T-AO#8]
Apesar de não definida nos documentos legais, Decreto Presidencial n.º 312/18,, nas FAQs da AGT, FAQ n.º 56, esta tag é definida com o nome "CUD" e, até definição posterior, deve ser preenchida com o valor "0".
No entanto esta tag não está definida no ficheiro XSD para os ficheiros "4.2. Movimentação de Mercadorias" (4.2.3.2) e "4.3. Documentos de Conferência" (4.3.4.2).

Nota: estranhamente não existe uma tag similar para o ficheiro "4.1. Documentos Comerciais".

**Comment by progsoftpack** [comment]
Além do que já foi referido pode-se verificar que essa tag também não consta para o ficheiro "4.4. Documentos de Recibos emitidos". Mas também não existe o índice do Campo n.º 4.4.4.2, será que está em falta o campo único de documento "CUD" ?

**Comment by cryptolopes** [comment]
Este elemento vai ser excluído.
