### ISSUE TITLE
Tratamento de Notas de créditos e débito no saft segundo alteração do Decreto 312

### ISSUE THREAD

**Issue by sebastiao39** [assoft-portugal/SAF-T-AO#81]
Bom dia Pessoal!

Pretendo dar entrada de Invoice do tipo nota de crédito ou nota de  débito noSaft(versão atualizada). Na versão anterior do saft dentro do Invoice era usado o campo InvoiceType onde hávia a possibilidade de especificar (NC, ND  e outros) mas na versão atual foi alterado para PurchaseType e não há possibilidade de fazer o tratamento de faturas a crédito ou débito por que as opções NC e ND não existem(o validador não considera este valor) a não ser FT,FR,GF,FG,AC,AR,AF,TV,NL,RC isso para o PurchaseType.

Se eu altero o PurchaseType para InvoiceType o validador obriga que o campo PurchaseType seja preenchido ou seja obriga a existência deste campo(PurchaseType). 

Então o que eu gostaria de saber é caso haja necessidade de fazer lançamento de Nota de crédito ou débito, como informo ao saft que este invoice refére-se a uma nota de crédito ou nota de débito.

Obrigado.

**Comment by cryptolopes** [comment]
> Se eu altero o PurchaseType para InvoiceType o validador obriga que o campo PurchaseType seja preenchido ou seja obriga a existência deste campo(PurchaseType).

Qual é o nó? `SalesInvoices` ou `PurchaseInvoices`?

**Comment by sebastiao39** [comment]
![image](https://user-images.githubusercontent.com/38100492/89689730-f01cd100-d8fc-11ea-98f6-893c51e40198.png)

**Comment by cryptolopes** [comment]
> A afirmação que acabei de fazer está certa cryptolopes?

Isso.

`InvoiceType` usa-se em `SalesInvoices`.

**Comment by Edson2001** [comment]
AuditFile.SourceDocuments.SalesInvoices.7Invoice (NC S2021/1) 
Porque esse erro?
![Captura de Tela (3)](https://user-images.githubusercontent.com/39365797/106247789-53cee980-6210-11eb-95c9-bc7bc3435e02.png)

**Comment by cryptolopes** [comment]
> AuditFile.SourceDocuments.SalesInvoices.7Invoice (NC S2021/1)

Se o `TaxPayable` for zero `0` o `NetTotal` tem de ser igual ao `GrossTotal`.
