### ISSUE TITLE
Erro (AGT) no ficheiro, AuditFile.SourceDocuments.SalesInvoices.2Invoice (VD1/2) Não deve conter IVA.

### ISSUE THREAD

**Issue by reactor-gonguela** [assoft-portugal/SAF-T-AO#84]
Recentemente o validador do portal da AGT emite o alerta **_ AuditFile.SourceDocuments.SalesInvoices.2Invoice (VD1/2) Não deve conter IVA_**. em facturas emitidas para o cliente genérico. A minha questão é: foi introduzida uma alteração na estrutura do saft em que o cliente genérico não deve facturar productos com IVA? Porque este alerta somente acontece com o cliente genérico (CustomerTaxid 999999999 ou XXXXXXXXX).
![safterror](https://user-images.githubusercontent.com/40264322/89796288-5b46ed00-db21-11ea-95cf-0278b1a18734.PNG)

**Comment by cryptolopes** [comment]
Copie para aqui os nós XML dos documentos `VD 1/1` e `VD 1/2`.

**Comment by reactor-gonguela** [comment]
<Invoice>
        <InvoiceNo>VD 1/1</InvoiceNo>
        <DocumentStatus>
          <InvoiceStatus>N</InvoiceStatus>
          <InvoiceStatusDate>2020-08-09T09:56:20</InvoiceStatusDate>
          <SourceID>4446d598-8993-469a-a977-75411f</SourceID>
          <SourceBilling>P</SourceBilling>
        </DocumentStatus>
        <Hash>bttRxZExbrEIKMQDKb8CtkqeZhU6kFYEyMn37l3dFzLB9jndnm5Bano2acWSE9/KE8RCXiRfeVgYRhkWJEnuuX546fDV7M3YdSckf80jLYgZkFbMxWZ2U8Kp/F6YCZULlurgQ4l+Abvtu0zC50+kBDPxIIwQnI5NN74ycvAc2Ro=</Hash>
        <HashControl>1</HashControl>
        <Period>8</Period>
        <InvoiceDate>2020-08-09</InvoiceDate>
        <InvoiceType>VD</InvoiceType>
        <SpecialRegimes>
          <SelfBillingIndicator>0</SelfBillingIndicator>
          <CashVATSchemeIndicator>0</CashVATSchemeIndicator>
          <ThirdPartiesBillingIndicator>0</ThirdPartiesBillingIndicator>
        </SpecialRegimes>
        <SourceID>4446d598-8993-469a-a977-75411f</SourceID>
        <SystemEntryDate>2020-08-09T09:56:20</SystemEntryDate>
        <CustomerID>037a2d42-65c0-450a-bf11-ebffb6</CustomerID>
        <Line>
          <LineNumber>1</LineNumber>
          <OrderReferences>
            <OriginatingON>VD 1/1</OriginatingON>
            <OrderDate>2020-08-09</OrderDate>
          </OrderReferences>
          <ProductCode>3</ProductCode>
          <ProductDescription>Ginguba 7888</ProductDescription>
          <Quantity>1.00</Quantity>
          <UnitOfMeasure>Caixa</UnitOfMeasure>
          <UnitPrice>1768.50</UnitPrice>
          <TaxPointDate>2020-08-09</TaxPointDate>
          <Description>Ginguba 7888</Description>
          <CreditAmount>1768.50</CreditAmount>
          <Tax>
            <TaxType>IVA</TaxType>
            <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>ISE</TaxCode>
            <TaxPercentage>0.00</TaxPercentage>
          </Tax>
          <TaxExemptionReason>Regime transitório </TaxExemptionReason>
          <TaxExemptionCode>M00</TaxExemptionCode>
        </Line>
        <Line>
          <LineNumber>2</LineNumber>
          <OrderReferences>
            <OriginatingON>VD 1/1</OriginatingON>
            <OrderDate>2020-08-09</OrderDate>
          </OrderReferences>
          <ProductCode>5</ProductCode>
          <ProductDescription>Computador HP 6789</ProductDescription>
          <Quantity>1.00</Quantity>
          <UnitOfMeasure>Item</UnitOfMeasure>
          <UnitPrice>437500.00</UnitPrice>
          <TaxPointDate>2020-08-09</TaxPointDate>
          <Description>Computador HP 6789</Description>
          <CreditAmount>437500.00</CreditAmount>
          <Tax>
            <TaxType>IVA</TaxType>
            <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>ISE</TaxCode>
            <TaxPercentage>0.00</TaxPercentage>
          </Tax>
          <TaxExemptionReason>Regime transitório </TaxExemptionReason>
          <TaxExemptionCode>M00</TaxExemptionCode>
        </Line>
        <DocumentTotals>
          <TaxPayable>0.00</TaxPayable>
          <NetTotal>439268.50</NetTotal>
          <GrossTotal>439268.50</GrossTotal>
          <Payment>
            <PaymentMechanism>CD</PaymentMechanism>
            <PaymentAmount>439268.50</PaymentAmount>
            <PaymentDate>2020-08-09</PaymentDate>
          </Payment>
        </DocumentTotals>
      </Invoice>
      <Invoice>

**Comment by cryptolopes** [comment]
Não existem propriamente erros de estrutura no XML.
Porém, importa, dizer que o `OrderReferences` é redondante e não há necessidade de o usar no caso em específico.

```xml
<OrderReferences>
  <OriginatingON>VD 1/1</OriginatingON>
  <OrderDate>2020-08-09</OrderDate>
</OrderReferences>
```

O regime transitório comporta `IVA`, certo? Se assim for, possivelmente, o erro apontado pela plataforma da AGT deve-se ao facto de os valores estarem calculados **sem IVA**.

**Comment by cryptolopes** [comment]
Podemos encerrar este Issue?
