### ISSUE TITLE
Pedido de esclarecimento

### ISSUE THREAD

**Issue by AfonsoMenata** [assoft-portugal/SAF-T-AO#91]
Olá, boa noite, pessoal.
Tenho uma dificuldade, a cerca da diferença entre o Recibo, como documento da tabela 4.1 e os recibos como Pagamento, tabela 4.4.
Exemplo:
-Nos documentos comerciais (SalesInvoice- 4.1), temos um tipo de documento "Recibo", co identificação "RE";
-Na tabela 4.4, temos Documentos de recibos emitidos.

A questão, é:
Se eu emiti um recibo de pagamento de uma factura, registo como INVOICE (Tabela 4.1), ou registo como Docuemto de Pagamento (Tabela 4.4)
???

Agradeço que me ajudem

**Comment by batalhadematos** [comment]
@AfonsoMenata Bom dia. Ou regista o recibo num lado ou no outro. Por exemplo, se for um talão de POS, ou uma F/R onde o mesmo documento  serve de recibo, deve usar o elemento payments em SalesInvoices. Se for o pagamento uma factura (que não serve de recibo), pode reportar em Documentos de Recibos Emitidos (Payments).

**Comment by cryptolopes** [comment]
> Ou regista o recibo num lado ou no outro. ❌

Não é bem assim.

> Por exemplo, se for um talão de POS, ou uma F/R onde o mesmo documento serve de recibo, deve usar o elemento payments em SalesInvoices. Se for o pagamento uma factura (que não serve de recibo), pode reportar em Documentos de Recibos Emitidos (Payments). ✔

### Recibo em SalesInvoices

O tipo de documento `InvoiceType` `RE` é usado apenas no **Setor Segurador**, quando se opte por não o fazer através do elemento `WorkingDocuments`. **Não deve ser usado pelos restantes sujeitos passivos para a emissão de documentos.**

A generalidade dos sujeitos passivos deve emitir Fatura/Recibo `FR` para documentos emitidos a pronto-pagamento. Quando assim for não há lugar à emissão de recibo `RC` no elemento `Payments`, tal como descreveu o @batalhadematos.

https://github.com/assoft-portugal/SAF-T-AO/blob/a0acb04ea1940f9a25db39665e700c9add5428bc/XSD/SAFTAO1.01_01.xsd#L1303-L1348

### Recibo em Payments

As restantes vendas feitas por intermédio dos tipos de documento `InvoiceType` `FT` `VD` `GF` `FG` `TV` devem dar lugar obrigatoriamente à emissão de um recibo `RC` em `Payments`.

https://github.com/assoft-portugal/SAF-T-AO/blob/a0acb04ea1940f9a25db39665e700c9add5428bc/XSD/SAFTAO1.01_01.xsd#L1925-L1939

**Comment by batalhadematos** [comment]
@cryptolopes Obrigado pela nota, mas quando eu refiro "recibo em SalesInvoices" me refiro ao registo do pagamento em SalesInvoices e não ao RE como tipo de factura.

**Comment by batalhadematos** [comment]
Espera @cryptolopes,
Da forma como colocas por dar margem para erro.
"_As restantes vendas feitas por intermédio dos tipos de documento InvoiceType FT VD GF FG TV devem dar lugar obrigatoriamente à emissão de um recibo RC em Payments._"

Aqui tem documentos que dão origem a recibo e documentos que não origem a recibo. Estes "pagamentos" reporto-os em partes diferentes. Exemplo:

TV = Talão de Vendas, ou o vulgo talão de POS, não dá lugar à emissão de recibo neste caso, reporto-o no Payments em SalesInvoices (4.1).
VD (Factura / Recibo) = Não dá lugar à emissão de recibo e também reporto-o em Payments do SalesInvoices (4.1).
FT = Dá lugar a emissão de um recibo e neste caso a factura reporto em SalesInvoices (4.1) e quando existir o respectivo pagamento, reporto-o em Payments (4.4)

Abraço

**Comment by AfonsoMenata** [comment]
@batalhadematos;
@cryptolopes ;
Muito obrigado à todos vós. VOssas contribuições foram formidáveis, porque focaram direitamente no entro da minha dificuldade.
