### ISSUE TITLE
Ajuda de interpretação dos campos do saft

### ISSUE THREAD

**Issue by AfonsoMenata** [assoft-portugal/SAF-T-AO#93]
Boa noite, Pessoal. Espero que estejam todos de saúde.

Eu estava lendo a estrutura do Saft AO e assim tenho a seguinte dificuldade:

Na tabela 4.4 - Documentos de Recibo emitidos (Payments), temos o campo 4.4.4.14 - Line. Lá temos compos sobre impostos, apartis do campo 4.4.4.14.16 (Imposto, taxa de imposto, Motivo de isenção...).
A questão é:
Se os impostos já foram cobrados e relatados na factura (Tabela 4-1 - SalesInvoice), já estão no saft. Então a quias impostos se referem no campo 4.4.4.1 - Line?????

Agradeço a vossa atenção e apreciação.

**Comment by cryptolopes** [comment]
Duplicate of #60 #70

**Comment by gury-shady** [comment]
Saudações gostaria de perceber no saft como fazer quando há notas de credito, agradeco a ajuda manos
