### ISSUE TITLE
Erro no ficheiro,AuditFile.SourceDocuments.WorkingDocuments.2WorkDocument (PP AGT2020/2) . Hash está errado.

### ISSUE THREAD

**Issue by Zetasoft930** [assoft-portugal/SAF-T-AO#95]
Bom dia.
Estava a testar o saf-t a 3 ou 4 dias atraz e me de parei com esse erro.Esta sempre ocorre sempre que tenho mas de uma factura porfoma no saf-t.

Conversei com outros programadores e esta acontecer o mesmo com eles,a te agora não sabemos de facto o porque o que esta a originar esse erro.

Por favor gostaria da vossa ajuda para resolver esse problema se for possivel
![Captura de ecrã de 2020-09-28 11-08-02](https://user-images.githubusercontent.com/61005215/94421492-89d66100-017d-11eb-9682-a581b568a9bb.png)

**Comment by cryptolopes** [comment]
Duplicate of #67
