### ISSUE TITLE
ERRO AO VALIDAR O SAFT-AO

### ISSUE THREAD

**Issue by AugCri** [assoft-portugal/SAF-T-AO#96]
Saudações a todo(a)s

**Erro no ficheiro,AuditFile.SourceDocuments.SalesInvoices.2Invoice (FR AAA2020/2) . Hash está errado.**

Estou a seguir as etapas de assinatura de facturas, tal como está na lei:

**1ª Factura Recibo:** 2020-10-03;2020-10-03T15:27:35;FR AAA2020/1;13680.00;

**RESULTADO DO 1º HASH:**

Fejo7OtV/OsC50ef8k8vYFu1Qy327ednJRcOOQ1InGxI6ui9uqmiVnohGQ3sh2UQKHtyipX9qOm+uzCRCJr92gel3ApRzLyLUhzpeblXBgnXhOuvYQoMpeNMVjUWaAvdH0jSXTaT0Y5rakSKuKKuqj9JLVs+ubVsDeosPnl5xiE=

**2ª Factura Recibo:** 2020-10-03;2020-10-03T15:30:17;FR AAA2020/2;13680.00;Fejo7OtV/OsC50ef8k8vYFu1Qy327ednJRcOOQ1InGxI6ui9uqmiVnohGQ3sh2UQKHtyipX9qOm+uzCRCJr92gel3ApRzLyLUhzpeblXBgnXhOuvYQoMpeNMVjUWaAvdH0jSXTaT0Y5rakSKuKKuqj9JLVs+ubVsDeosPnl5xiE=

**RESULTADO DO 2º HASH:**

HcoDZizVAr+pnHOZ7zYL/5MkM63Pyi7usdMFUtGtfzqXwN3rEvjt/1pDmEOM90KR3dp/pmGiTHtF60ZVoQcEArunm6pdvqGU/1bz4D5e5Wd+efY2jM2dJxIru8bBp9f1kTaTNQan3HOKTQjuNYZRrXW25DOgFdlVnw5FRrCroxc=

Será que estou a fazer algo de errado?

Quando testo o xml no portal da AGT, recebo o erro do segundo hash. 

Será que existe algum problema com o portal da AGT?
Por favor preciso de ajuda.

Agradecido

**Comment by cryptolopes** [comment]
- [Pesquisar a solução em Issues fechados](https://github.com/assoft-portugal/SAF-T-AO/issues?q=Hash)
