### ISSUE TITLE
Erro do sistema-001

### ISSUE THREAD

**Issue by ITECLDA** [assoft-portugal/SAF-T-AO#97]
**Describe your question**
Boa tarde carrissimo, somo da empresa Itec LDA, pertencentes ao software Minerva, gostariamos de saber o porque que estamos a ter o erro (Erro do sistema-001) em algumas empresa guando faz se o upload  SAF-t. em outras esta tudo bem a funcionar.....

**Comment by cryptolopes** [comment]
- [**Contactos do Portal do Contribuinte**](https://portaldocontribuinte.minfin.gov.ao/contactos)

Neste repositório é só SAF-T.

**Comment by rpgcvc** [comment]
Caro ITECLDA, chegou a alguma resposta sobre esse erro? Também estou a passar pelo mesmo....
