### ISSUE TITLE
CreditAmount mal calculado

### ISSUE THREAD

**Issue by inmx** [assoft-portugal/SAF-T-AO#98]
O campo <UnitOfMeasure>, não está a reconhecer a unidade de medida pretendido, "%"

Estou a receber o seguinte erro:
CreditAmount mal calculado.

Segue um trecho do código:
<Line>
          <LineNumber>1</LineNumber>
          <ProductCode>21</ProductCode>
          <ProductDescription>Desc. Serviço</ProductDescription>
          <Quantity>1</Quantity>
          <UnitOfMeasure>%</UnitOfMeasure>
          <UnitPrice>2300000.00</UnitPrice>
          <TaxPointDate>2020-10-06</TaxPointDate>
          <Description>Desc. Serviço </Description>
          <CreditAmount>23000.00</CreditAmount>
          <Tax>
            <TaxType>IVA</TaxType>
            <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>ISE</TaxCode>
            <TaxPercentage>0</TaxPercentage>
          </Tax>
          <TaxExemptionReason>
          Regime transitorio
     <TaxExemptionReason>
   <TaxExemptionCode>M00<TaxExemptionCode>
</Line>

========================
Como proceder para que o validador reconheça a unidade pretendido?

**Comment by inmx** [comment]
O campo `<UnitOfMeasure>`, não está a reconhecer a unidade de medida pretendido, "%"

Estou a receber o seguinte erro:
CreditAmount mal calculado.

Segue um trecho do código:
`<Line>
          <LineNumber>1</LineNumber>
          <ProductCode>21</ProductCode>
          <ProductDescription>Desc. Serviço</ProductDescription>
          <Quantity>1</Quantity>
          <UnitOfMeasure>%</UnitOfMeasure>
          <UnitPrice>2300000.00</UnitPrice>
          <TaxPointDate>2020-10-06</TaxPointDate>
          <Description>Desc. Serviço </Description>
          <CreditAmount>23000.00</CreditAmount>
          <Tax>
            <TaxType>IVA</TaxType>
        <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>ISE</TaxCode>
            <TaxPercentage>0</TaxPercentage>
          </Tax>
          <TaxExemptionReason>
          Regime transitorio
     <TaxExemptionReason>
   <TaxExemptionCode>M00<TaxExemptionCode>
</Line>
`

========================
Como proceder para que o validador reconheça a unidade pretendido?

**Comment by cryptolopes** [comment]
@inmx 

```javascript
CreditAmount == UnitPrice * Quantity
```

**Comment by inmx** [comment]
`CreditAmount == UnitPrice * Quantity` é ali onde começa o problema, está fórmula é aplicável para sistemas de facturação simples já para sistemas mais complexos como é o nosso caso para facturação de serviços para empresas de construção civil, onde os clientes definem as unidades de medidas e as fórmulas de cálculo para as respectivas unidades de medidas, neste caso como proceder

`
Exemplo:
Unidade: "%" = percentual
Pu: 300 akz;
Qtd: 14;
CreditAmount: 42 akz que corresponde aos 14% do PU`

Se aplicar a fórmula trivial : `CreditAmount = Pu*Qtd` irá multiplicar e não é isso que se quer, lembrando lhes que ainda existe outras unidades de medidas usadas pelo sector de construção civil, ajude-nos como devemos proceder

**Comment by cryptolopes** [comment]
@inmx A fórmula é sempre a mesma, não importa a complexidade da app. Os têm de respeitar o schema. No caso são inteiros. Qtd: 0.14.

**Comment by inmx** [comment]
Ok, muito obrigado
