### ISSUE TITLE
Erro no ficheiro, AuditFile.MasterFiles.2Customer.CustomerTaxID é inválido. porque que esse esta acontecer agora?

### ISSUE THREAD

**Issue by Zetasoft930** [assoft-portugal/SAF-T-AO#99]
Durante   semana passada eu testei o saf-t e nunca deu esse erro .gostaria de saber se mudaram alguma coisa.
porque mesmo colocando um nif de um cliente valido continua a dar esse erro.

**Comment by Zetasoft930** [comment]
![Captura de Tela (120)](https://user-images.githubusercontent.com/61005215/95745281-ae0d6400-0c8c-11eb-9677-bada9f69b7ff.png)

**Comment by cryptolopes** [comment]
@Zetasoft930 XML de exemplo, por favor.

**Comment by Nonius2020** [comment]
Os nosso clientes estão a ter erros semelhantes aquando da submissão dos ficheiros em produção.
> Erro no ficheiro, AuditFile.MasterFiles.278Customer.CustomerTaxID é inválido.
(...)

Quando submetemos um ficheiro no validador, para testar, os erros são mais detalhados e indicam:
> AuditFile.MasterFiles.2Customer.CustomerTaxID(João Matos) está repetido com o NIF do cliente (Mário Gomes).
(...)

Aparentemente passou a ser imposto que na tabela de clientes não possam existir vários registos `Customer` com o mesmo `CustomerTaxID`.
Essa regra não faz sentido, na medida em que, por exemplo, para cada documento emitido sem número de contribuinte a clientes passantes (sem ficha de cliente), é criado um registo `Customer` com o `CustomerTaxID` igual a `XXXXXXXXXXX`, pelo que, a duplicação é inevitável.
> **FT-1** Nome: João NIF: XXXXXXXXXXX
**FT-2** Nome: Manuel NIF: XXXXXXXXXXX
**FT-3** Nome: Carlos NIF: XXXXXXXXXXX

A duplicação de  `CustomerTaxID` também ocorre quando um cliente passante (sem ficha aberta) fornece o mesmo NIF para a emissão de vários documentos, mas indica um nome diferente ou uma morada diferente em vários dos documentos.
> **FT-4** Nome: João Gomes NIF: 1234567890
**FT-5** Nome: J. Gomes NIF: 1234567890

**Comment by batalhadematos** [comment]
Bom dia a todos.
Aproveitando que o issue ainda está aberto.
Estranhamente também comecei a ter erros no CustomerTaxID e já estou de alguma forma perdido.

Fiz alguns testes e utilizei os seguintes NIF's (alguns números aleatórios e alguns válidos):

- **002703521BA038** --- Gera erro;
- 5854587854 --- Gera erro;
- 5558887778 --- Gera erro;
- 5000579769 --- Gera erro;
- 5415558784  --- Gera erro;
- **5417576204** --- PASSOU;
- **99999999999**  --- Gera erro;

Da lista acima:
O primeiro e penúltimos NIF são válidos (estão registados na AGT como válidos e activos). Acontece porém que no primeiro gera erro.
O NIF "99999999999" é válido e faz parte da Lei 312.18. Estranhamente está a gerar erro. Experimentei também com 10x9 e o mesmo acontece.

Os restantes 4 NIF (2º a 4º), são números aleatórios que inseri e gera erro em todos.

As minhas questões (assumindo que não há problemas no portal de produtores):
- No processo de validação do SAF-T, foi implementado algum processo novo de verificação da validade do NIF? Se sim, qual de formas a qe possamos prevenir esses erros?
- Que se passa com o NIF "002703521BA038" que é válido e consta da base de dados da AGT como activo e com o NIF do Consumidor Final?

Provavelmente nos grupos do Telegram e WhatsApp estejam as respostas a estas perguntas mas aí fica muito difícil localizar.

Obrigado

Paulo Matos

**Comment by Gilberto-Alberto** [comment]
@batalhadematos bom dia caro Matos, esse problema não é um caso isolado tambem passo por isso. Mas fico ainda mais triste quando nao recebemos um retorno da AGT sobre esse problema tecnico

**Comment by Marcosinffoco** [comment]
Já notei que o problema é genérico.  Em todos os clientes que esta sendo testado, o resultado é este também.
Acho que o sistema anda a comparar com nifs do sistema dele.  Alguns NIFs, acredito eu, que os vossos fornecedores devem ter NIFs actualizados,  pois em uns já tinha visto isto, mas nos demais, o problema persiste.

Se eu fosse validar o sistema hoje, tenho plena certeza que iria ser reprovado por ter uma elevada quantidade de registos em falhas.

Outra é esta situação da Razão da isenção, que agora tem que esta exatamente como esta na tabela.  Com acentuações, Caracteres especias, etc

É uma chatice , pois o meu sistema quando gera, tem problemas no momento da conversão para XML quando a string tem estes caracteres.   Eu tive que usar uma função para retirar estes caracteres para gerar sem problemas.   E foi assim desde 2019 quando iniciei os testes.  

Agora em 2020, neste ultimo mês, vieram com esta novidade um pouco inconveniente. 
Entendo que é para padronizar os textos e não ter nada de divergente que não esteja na tabela Tax Exemption Codes. 

Bem que o pessoal da AGT poderia dar uma declaração a respeito disto.
